LANSA.addComponent({id:"XD2LOGIN",nm:"XD2Login",ot:"rp",tp:"Reusable Part",de:"Login",tl:14020000},function(l,oI,u){var rc1=l.cB("xd2img09.png");var cO=l.rC(oI,{an:"PRIM_PPNL",co:function(){cO.aN.call(this);var C0=this.cR("STYLESHROUD","PRIM_VS","Style");var C1=this.cR("BRUSH1","PRIM_VS","SolidBrush");var C2=this.cR("STYLEINVALID","PRIM_VS","Style");var C3=this.cR("STYLEINVALIDBRUSH","PRIM_VS","SolidBrush");var C4=this.cR("STYLELOGIN","PRIM_VS","Style");var C5=this.cR("STYLEPOPUP","PRIM_VS","Style");
var C6=this.cR("STYLETITLE","PRIM_VS","Style");var C7=this.cR("STYLETITLEBRUSH","PRIM_VS","SolidBrush");var C8=this.cR("LAYOUT","PRIM_TBLO");var C9=this.cR("COLUMN1","PRIM_TBLO","Column");var C10=this.cR("ROW1","PRIM_TBLO","Row");var C11=this.cR("LAYOUTITEM1","PRIM_TBLO","Item");var C12=this.cR("LAYOUTITEM2","PRIM_TBLO","Item");var C13=this.cR("LAYOUTITEM3","PRIM_TBLO","Item");var C14=this.cR("LAYOUTITEM4","PRIM_TBLO","Item");var C15=this.cR("LAYOUTITEM5","PRIM_TBLO","Item");var C16=this.cR("EDIT_USER","PRIM_EDIT");
var C17=this.cR("EDIT_PASSWORD","PRIM_EDIT");var C18=this.cR("LABEL_ERROR","PRIM_LABL");var C19=this.cR("LOGIN","PRIM_PHBN");var C20=this.cR("LABEL1","PRIM_LABL");var C21=this.cR("CLOSE","PRIM_IMAG");var C22=this.cA("APPLICATION","XD2APP");C0.setBackgroundBrush(C1);C0.iC();C1.setColor("0:0:0");C1.setOpacity(50);C1.iC();C2.setForegroundBrush(C3);C2.setItalic(true);C2.iC();C3.setColor("255:21:3");C3.iC();C4.setCornerBottomLeft(10);C4.setCornerBottomRight(10);C4.setCornerTopLeft(10);C4.setCornerTopRight(10);
C4.iC();C5.setBorderBottom(1);C5.setBorderLeft(1);C5.setBorderRight(1);C5.setBorderTop(1);C5.setEffect(null);C5.iC();C6.setFontSize(150);C6.setFontUnits("PERCENT");C6.setForegroundBrush(C7);C6.iC();C7.setColor("107:107:107");C7.iC();C8.iC();C9.setDisplayPosition(1);C9.setParent(C8);C9.iC();C10.setDisplayPosition(1);C10.setParent(C8);C10.iC();C11.setColumn(C9);C11.setFlow("RIGHT");C11.setManage(C19);C11.setParent(C8);C11.setRow(C10);C11.setSizing("FITTOWIDTH");C11.setAlignment("BOTTOMRIGHT");C11.setMarginBottom(10);
C11.setMarginRight(10);C11.setMarginLeft(10);C11.iC();C12.setAlignment("TOPCENTER");C12.setColumn(C9);C12.setFlow("DOWN");C12.setManage(C16);C12.setParent(C8);C12.setRow(C10);C12.setSizing("FITTOWIDTH");C12.setMarginTop(10);C12.setMarginLeft(10);C12.setMarginRight(10);C12.iC();C13.setAlignment("TOPCENTER");C13.setColumn(C9);C13.setFlow("DOWN");C13.setManage(C17);C13.setParent(C8);C13.setRow(C10);C13.setSizing("FITTOWIDTH");C13.setMarginTop(10);C13.setMarginLeft(10);C13.setMarginRight(10);C13.iC();
C14.setColumn(C9);C14.setManage(C18);C14.setParent(C8);C14.setRow(C10);C14.setSizing("FITTOWIDTH");C14.setAlignment("TOPCENTER");C14.setFlow("DOWN");C14.setMarginLeft(10);C14.setMarginRight(10);C14.iC();C15.setAlignment("TOPCENTER");C15.setColumn(C9);C15.setManage(C20);C15.setParent(C8);C15.setRow(C10);C15.setSizing("FITTOWIDTH");C15.setFlow("DOWN");C15.setMarginLeft(10);C15.setMarginRight(10);C15.setMarginTop(10);C15.setMarginBottom(5);C15.iC();C16.setDisplayPosition(4);C16.setParent(this);C16.setShowSelection(false);
C16.setShowSelectionHilight(false);C16.setTabPosition(1);C16.setWidth(323);C16.setHeight(40);C16.setPlaceholder("User");C16.setTop(64);C16.iC();C17.setDisplayPosition(5);C17.setParent(this);C17.setShowSelection(false);C17.setShowSelectionHilight(false);C17.setTabPosition(2);C17.setTop(114);C17.setWidth(323);C17.setHeight(40);C17.setPlaceholder("Password");C17.setPasswordChar("*");C17.iC();C18.setDisplayPosition(6);C18.setEllipses("WORD");C18.setHeight(25);C18.setParent(this);C18.setTabPosition(3);
C18.setTabStop(false);C18.setTop(154);C18.setVerticalAlignment("CENTER");C18.setWidth(323);C18.setStyle(C2);C18.setCaption("Your session has timed out. Please sign in again.");C18.iC();C19.setCaption("Login");C19.setDisplayPosition(3);C19.setParent(this);C19.setTabPosition(4);C19.setTop(198);C19.setHeight(47);C19.setWidth(323);C19.setThemeDrawStyle("MediumTitle");C19.setStyle(C4);C19.iC();C20.setCaption("Login");C20.setDisplayPosition(2);C20.setEllipses("WORD");C20.setHeight(39);C20.setParent(this);
C20.setTabPosition(5);C20.setTabStop(false);C20.setVerticalAlignment("CENTER");C20.setWidth(323);C20.setStyle(C6);C20.iC();C21.setDisplayPosition(1);C21.setHeight(20);C21.setImage(rc1);C21.setLeft(312);C21.setParent(this);C21.setTabPosition(6);C21.setTabStop(false);C21.setTop(19);C21.setWidth(20);C21.setThemeDrawStyle("ToolbarButton");C21.iC();if((C22!=null)&&(C22.iI()==false)){C22.iC();}C16.aH("CHANGED",this,e1);C16.aH("ENTER",this,e3);C17.aH("CHANGED",this,e1);C17.aH("ENTER",this,e3);C19.aH("CLICK",this,e3);
C21.aH("CLICK",this,e6);C22.aH("INVALIDLOGIN",this,e4);C22.aH("SESSIONTIMEOUT",this,e5);C22.aH("LOGGEDIN",this,e6);this.setHeight(257);this.setLeft(0);this.setTop(0);this.setWidth(345);this.setShroudStyle(C0);this.setCloseButton(true);this.setLayoutManager(C8);this.setAutoFocus(true);this.setAutoClose(false);this.setTitleBarThemeDrawStyle(" ");this.setStyle(C5);this.setThemeDrawStyle("Font");this.aH("CREATEINSTANCE",this,e1);this.aH("CLOSED",this,e2);}});function e1(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#COM_OWNER.CreateInstance #Edit_User.Changed #Edit_Password.Changed",40);
r.ln=40;{r.ln=42;m.LABEL_ERROR.set("");}r.ln=44;r.e();};function e2(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#COM_OWNER.Closed",46);r.ln=46;{r.ln=48;m.LABEL_ERROR.set("");m.EDIT_USER.set("");m.EDIT_PASSWORD.set("");}r.ln=50;r.e();};function e3(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Login.Click #Edit_User.Enter #Edit_Password.Enter",52);r.ln=52;{r.ln=54;m.APPLICATION.ref.mthLOGIN(m.EDIT_USER.get(),m.EDIT_PASSWORD.get());}r.ln=56;r.e();};function e4(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Application.InvalidLogin",58);
r.ln=58;{r.ln=60;m.LABEL_ERROR.set("Invalid user or password");}r.ln=62;r.e();};function e5(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Application.SessionTimeOut",64);r.ln=64;{r.ln=66;m.EDIT_USER.set(m.APPLICATION.ref.getACTIVEUSER());r.ln=68;m.LABEL_ERROR.set("Your session has timed out. Please sign in again.");}r.ln=70;r.e();};function e6(sender,Ps){var r=l.eR(this,cO,"#Application.LoggedIn #Close.Click",72);r.ln=72;{r.ln=74;this.mthCLOSEPOPUP();}r.ln=76;r.e();};},{rc:["XD2APP"],rp:["PRIM_PPNL","PRIM_VS.Style","PRIM_VS.SolidBrush","PRIM_TBLO","PRIM_TBLO.Column","PRIM_TBLO.Row","PRIM_TBLO.Item","PRIM_EDIT","PRIM_LABL","PRIM_PHBN","PRIM_IMAG"]
});