LANSA.addComponent({id:"XD2HEAD",nm:"XD2Header",ot:"rp",tp:"Reusable Part",de:"Header",tl:14010003},function(l,oI,u){var rc1=l.cB("xd2img05.png");var rc2=l.cB("xd2img04.png");var cO=l.rC(oI,{an:"PRIM_PANL",co:function(){cO.aN.call(this);var C0=this.cR("STYLE1","PRIM_VS","Style");var C1=this.cR("HEADERLAYOUT","PRIM_TBLO");var C2=this.cR("HEADERLAYOUTCOLUMN1","PRIM_TBLO","Column");var C3=this.cR("HEADERLAYOUTROW1","PRIM_TBLO","Row");var C4=this.cR("HEADERLAYOUTTITLEITEM","PRIM_TBLO","Item");var C5=this.cR("HEADERLAYOUTMENUBARITEM","PRIM_TBLO","Item");
var C6=this.cR("HEADERLAYOUTLOGINITEM","PRIM_TBLO","Item");var C7=this.cR("LABEL_TITLE","PRIM_LABL");var C8=this.cR("LABEL_LOGIN","PRIM_LABL");var C9=this.cR("MENUBAR","PRIM_PPNL","MenuBar");var C10=this.cR("MENU_HOME","PRIM_PPNL","MenuItem");var C11=this.cR("MENU_ABOUT","PRIM_PPNL","MenuItem");var C12=this.cR("MENU_CONTACT","PRIM_PPNL","MenuItem");var C13=this.cA("APPLICATION","XD2APP");C0.setCursor("HAND");C0.iC();C1.iC();C2.setDisplayPosition(1);C2.setParent(C1);C2.iC();C3.setDisplayPosition(1);
C3.setParent(C1);C3.iC();C4.setAlignment("CENTERLEFT");C4.setColumn(C2);C4.setManage(C7);C4.setParent(C1);C4.setRow(C3);C4.setSizing("FITTOHEIGHT");C4.setColumnSpan(2);C4.setFlow("RIGHT");C4.setMarginBottom(10);C4.iC();C5.setAlignment("CENTERLEFT");C5.setColumn(C2);C5.setParent(C1);C5.setRow(C3);C5.setManage(C9);C5.setSizing("NONE");C5.setFlow("RIGHT");C5.setMarginRight(5);C5.setMarginLeft(5);C5.setMarginBottom(5);C5.iC();C6.setColumn(C2);C6.setManage(C8);C6.setParent(C1);C6.setRow(C3);C6.setSizing("CONTENTWIDTH");
C6.setAlignment("BOTTOMRIGHT");C6.setFlow("UP");C6.setMarginBottom(5);C6.iC();C7.setDisplayPosition(3);C7.setEllipses("WORD");C7.setParent(this);C7.setTabPosition(2);C7.setTabStop(false);C7.setWidth(550);C7.setCaption("NAME OF SITE");C7.setThemeDrawStyle("Title+TitleText");C7.setLeft(55);C7.setTop(0);C7.setVerticalAlignment("CENTER");C7.setHeight(60);C7.iC();C8.setCaption("Login");C8.setDisplayPosition(2);C8.setEllipses("WORD");C8.setLeft(607);C8.setParent(this);C8.setTabPosition(3);C8.setTabStop(false);
C8.setVerticalAlignment("BOTTOM");C8.setWidth(74);C8.setMarginRight(10);C8.setMouseOverStyle(C0);C8.setMarginLeft(10);C8.setHeight(40);C8.setImage(rc1);C8.setTop(30);C8.iC();C9.setDisplayPosition(1);C9.setParent(this);C9.setTabPosition(1);C9.setTabStop(false);C9.setWidth(45);C9.setHeight(45);C9.setCollapseStyle("ALL");C9.setTop(8);C9.setLeft(5);C9.iC();C10.setCaption("HOME");C10.setDisplayPosition(1);C10.setHeight(45);C10.setParent(C9);C10.setTabPosition(1);C10.setTabStop(false);C10.setWidth(200);
C10.setAlignment("CENTER");C10.setThemeDrawStyle("MenuSelected");C10.iC();C11.setCaption("ABOUT");C11.setDisplayPosition(2);C11.setHeight(45);C11.setLeft(200);C11.setParent(C9);C11.setTabPosition(3);C11.setTabStop(false);C11.setWidth(200);C11.setAlignment("CENTER");C11.iC();C12.setCaption("CONTACT");C12.setDisplayPosition(3);C12.setHeight(45);C12.setLeft(400);C12.setParent(C9);C12.setTabPosition(2);C12.setTabStop(false);C12.setWidth(200);C12.setAlignment("CENTER");C12.iC();if((C13!=null)&&(C13.iI()==false))
{C13.iC();}C8.aH("CLICK",this,e8);C9.aH("PREPARE",this,e11);C10.aH("CLICK",this,e5);C11.aH("CLICK",this,e6);C12.aH("CLICK",this,e7);C13.aH("DESKTOPVIEW",this,e1);C13.aH("TABLETVIEW",this,e1);C13.aH("MOBILEVIEW",this,e1);C13.aH("SHOWHOME",this,e2);C13.aH("SHOWABOUT",this,e3);C13.aH("SHOWCONTACT",this,e4);C13.aH("LOGGEDIN",this,e9);C13.aH("LOGGEDOUT",this,e10);this.setDisplayPosition(1);this.setLeft(0);this.setTabPosition(1);this.setTop(0);this.setWidth(681);this.setLayoutManager(C1);this.setHeight(70);
}});function e1(sender,Ps){var r=l.eR(this,cO,"#Application.DesktopView #Application.TabletView #Application.MobileView",28);r.ln=28;{r.ln=30;this.setHeight(70);}r.ln=32;r.e();};function e2(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Application.ShowHome",34);r.ln=34;{r.ln=36;for(var i1=m.MENUBAR.getComponentControls().cI();i1.step();){i1.item().setThemeDrawStyle("")};r.ln=37;m.MENU_HOME.setThemeDrawStyle("MenuSelected");}r.ln=39;r.e();};function e3(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Application.ShowAbout",41);
r.ln=41;{r.ln=43;for(var i1=m.MENUBAR.getComponentControls().cI();i1.step();){i1.item().setThemeDrawStyle("")};r.ln=44;m.MENU_ABOUT.setThemeDrawStyle("MenuSelected");}r.ln=46;r.e();};function e4(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Application.ShowContact",48);r.ln=48;{r.ln=50;for(var i1=m.MENUBAR.getComponentControls().cI();i1.step();){i1.item().setThemeDrawStyle("")};r.ln=51;m.MENU_CONTACT.setThemeDrawStyle("MenuSelected");}r.ln=53;r.e();};function e5(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Menu_Home.Click",55);
r.ln=55;{r.ln=57;m.APPLICATION.ref.mthSHOW_HOME();}r.ln=59;r.e();};function e6(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Menu_About.Click",61);r.ln=61;{r.ln=63;m.APPLICATION.ref.mthSHOW_ABOUT();}r.ln=65;r.e();};function e7(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Menu_Contact.Click",67);r.ln=67;{r.ln=69;m.APPLICATION.ref.mthSHOW_CONTACT();}r.ln=71;r.e();};function e8(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Label_Login.Click",73);r.ln=73;{r.ln=75;if(l.s.eq(m.LABEL_LOGIN.get(),"Login")){r.ln=77;
m.APPLICATION.ref.mthSHOWLOGINDIALOG();}else{r.ln=81;m.APPLICATION.ref.mthLOGOUT();}}r.ln=85;r.e();};function e9(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Application.LoggedIn",87);r.ln=87;{r.ln=89;m.LABEL_LOGIN.set(l.cat(m.APPLICATION.ref.getACTIVEUSER()," logged in.   "));r.ln=90;m.LABEL_LOGIN.setImage(rc2);r.ln=91;m.LABEL_LOGIN.set(l.cat(m.LABEL_LOGIN.get(),"Log Out"));}r.ln=93;r.e();};function e10(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Application.LoggedOut",95);r.ln=95;{r.ln=97;m.LABEL_LOGIN.setImage(rc1);
r.ln=98;m.LABEL_LOGIN.set("Login");}r.ln=100;r.e();};function e11(sender,Ps){var r=l.eR(this,cO,"#MenuBar.Prepare",102);var P0=Ps.r("LEFT");var P1=Ps.r("TOP");var P2=Ps.r("WIDTH");var P3=Ps.r("HEIGHT");var P4=Ps.r("TRANSITION");r.ln=102;{r.ln=104;P1.set(0);r.ln=105;P0.set(0);r.ln=106;P2.set(150);r.ln=107;P3.set(l.WEB().getWebPage().getHeight());r.ln=108;P4.set("SLIDEINLEFT");}r.ln=110;r.e();};},{rc:["XD2APP"],rp:["PRIM_PANL","PRIM_VS.Style","PRIM_TBLO","PRIM_TBLO.Column","PRIM_TBLO.Row","PRIM_TBLO.Item","PRIM_LABL","PRIM_PPNL.MenuBar","PRIM_PPNL.MenuItem"]
});