LANSA.addComponent({id:"XDEMOW_30",nm:"xDemoWebImageDownload",ot:"wp",tp:"Web Page",de:"Image Multiple DownLoad",tl:14010003},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")||(l.gCL()=="LLL")){cL=l.gCL();}var rc1=l.cB("ximaged_3.png");var Fd={F1:{nm:"EMPNO",ft:"A",ln:5,dc:0,lb:{"ENG":"Employee no....","FRA":"No employé  . .","JPN":"Employee no....","LLL":"Employee no...."}[cL],h1:{"ENG":"  Employ","FRA":"Salarié","JPN":"  Employ","LLL":"  Employ"}[cL],h2:{"ENG":"  Number","FRA":" ","JPN":"  Number","LLL":"  Number"}[cL],
h3:" ",de:{"ENG":"Employee Number","FRA":"Numéro d´employé","JPN":"Employee Number","LLL":"Employee Number"}[cL],dv:"",ia:["FE"]},F2:{nm:"SURNAME",ft:"A",ln:20,dc:0,ks:"O",lb:"Surname........",h1:"Surname",h2:"",h3:"",de:"Employee Surname",dv:"",ia:["FE","LC"]},F3:{nm:"GIVENAME",ft:"A",ln:20,dc:0,ks:"O",lb:"Given names....",h1:"Given name(s)",h2:"",h3:"",de:"Employee Given Name(s)",dv:"",ia:["FE","LC"]},F4:{nm:"DEPTDESC",ft:"A",ln:20,dc:0,ks:"O",lb:{"ENG":"Description....","FRA":"Description . .","JPN":"Description....","LLL":"Description...."}[cL],
h1:{"ENG":"Department","FRA":"Description","JPN":"Department","LLL":"Department"}[cL],h2:{"ENG":"Description","FRA":"Département","JPN":"Description","LLL":"Description"}[cL],h3:" ",de:{"ENG":"Department Description","FRA":"Département","JPN":"Department Description","LLL":"Department Description"}[cL],dv:"",ia:["FE","LC"]}};var cO=l.rC(oI,{an:"PRIM_WEB",fd:Fd,mt:{Download:{}},co:function(){cO.aN.call(this);var f=this.aF("XDEMOW_30",Fd);var C0=this.cA("GDATA","XDEMO_30");var C1=this.cR("STYLE1","PRIM_VS","Style");
var C2=this.cR("BRUSH1","PRIM_VS","SolidBrush");var C3=this.cR("TABLELAYOUT","PRIM_TBLO");var C4=this.cR("COLUMN","PRIM_TBLO","Column");var C5=this.cR("ROW1","PRIM_TBLO","Row");var C6=this.cR("LIST","PRIM_LIST");var C7=this.cR("LAYOUTITEM","PRIM_TBLO","Item");var C8=this.cR("COLUMNIMAGE","PRIM_LIST","Image");var C9=this.cR("COLUMNEMPNO","PRIM_LIST","String");var C10=this.cR("COLUMNSURNAME","PRIM_LIST","String");var C11=this.cR("COLUMNGIVENAME","PRIM_LIST","String");var C12=this.cR("COLUMNDOWNLOAD","PRIM_LIST","Button");
if((C0!=null)&&(C0.iI()==false)){C0.iC();}C1.setBackgroundBrush(C2);C1.setCornerTopLeft(3);C1.setCornerBottomLeft(3);C1.setCornerTopRight(3);C1.setCornerBottomRight(3);C1.iC();C2.setColor("214:214:214");C2.iC();C3.iC();C4.setDisplayPosition(1);C4.setParent(C3);C4.iC();C5.setDisplayPosition(1);C5.setParent(C3);C5.iC();C6.setDisplayPosition(1);C6.setHeight(800);C6.setLeft(0);C6.setParent(this);C6.setTabPosition(1);C6.setTop(0);C6.setWidth(1200);C6.setRowHeight(37);C6.setRowResize(true);C6.setSelectionStyle("ALL");
C6.setRowLines(false);C6.setColumnLines(false);C6.iC();C7.setColumn(C4);C7.setManage(C6);C7.setParent(C3);C7.setRow(C5);C7.iC();C8.setColumnWidth(50);C8.setDisplayPosition(1);C8.setParent(C6);C8.setImageSizing("BESTFIT");C8.setCellMarginBottom(2);C8.setCellMarginLeft(2);C8.setCellMarginRight(2);C8.setCellMarginTop(2);C8.iC();C9.setDisplayPosition(2);C9.setParent(C6);C9.setSource(f.F1);C9.setColumnCaption("Emp #");C9.setColumnWidth(78);C9.setSortOnClick(true);C9.setColumnCaptionType("CAPTION");C9.iC();
C10.setDisplayPosition(3);C10.setParent(C6);C10.setSource(f.F2);C10.setSortOnClick(true);C10.iC();C11.setDisplayPosition(4);C11.setParent(C6);C11.setSource(f.F3);C11.setSortOnClick(true);C11.setColumnWidth(161);C11.iC();C12.setColumnWidth(113);C12.setDisplayPosition(5);C12.setParent(C6);C12.setImage(rc1);C12.setCaption("Download");C12.setCellSizing("NONE");C12.setCellWidth(100);C12.setStyle(C1);C12.setColumnCaption("DownLoad");C12.iC();C0.aH("PREPARED",this,e1);C6.aH("ITEMMOUSEENTER",this,e3);C6.aH("ITEMMOUSELEAVE",this,e4);
C12.aH("CLICK",this,e2);this.setLayoutManager(C3);}});function e1(sender,Ps){var f=this.FLD.XDEMOW_30,m=this.REF,r=l.eR(this,cO,"#gData.Prepared",27);r.ln=27;{r.ln=30;{var i1=m.GDATA.ref.getEMPLOYEES().cI();while(i1.step()){var EMPLOYEE=r.sR("EMPLOYEE",i1.item());r.ln=33;f.F1.set(EMPLOYEE.getID());r.ln=34;f.F2.set(EMPLOYEE.getSURNAME());r.ln=35;f.F3.set(EMPLOYEE.getGIVENNAME());r.ln=36;f.F4.set(EMPLOYEE.getDEPARTMENT().getDESCRIPTION());r.ln=38;m.LIST.addEntry();r.ln=41;m.COLUMNIMAGE.getCurrentItem().setImage(EMPLOYEE.getTHUMBNAIL());
r.ln=43;m.COLUMNDOWNLOAD.getCurrentItem().setVisible(false);r.ln=44;m.COLUMNDOWNLOAD.getCurrentItem().setHint("Download Image");r.ln=46;}i1.end();r.dR("EMPLOYEE");}}r.ln=48;r.e();};function e2(sender,Ps){var r=l.eR(this,cO,"#ColumnDownload.Click",50);r.ln=50;{r.ln=52;this.mthDOWNLOAD();}r.ln=54;r.e();};cO.mthDOWNLOAD=function(){var f=this.FLD.XDEMOW_30,r=l.mR(this,cO,"Download",56);var C0=r.cRR("IMAGEDOWNLOAD","XDEMODATA","DOWNLOADIMAGE");C0.iC();r.ln=56;{r.ln=60;C0.mthEXECUTE({FLD:{"EMPNO":f.F1.get()}},{});
}r.ln=62;r.e();};function e3(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#List.ItemMouseEnter",64);r.ln=64;{r.ln=66;m.COLUMNDOWNLOAD.getCurrentItem().setVisible(true);}r.ln=68;r.e();};function e4(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#List.ItemMouseLeave",70);r.ln=70;{r.ln=72;m.COLUMNDOWNLOAD.getCurrentItem().setVisible(false);}r.ln=74;r.e();};},{rc:["XDEMO_30"],rp:["PRIM_WEB","PRIM_VS.Style","PRIM_VS.SolidBrush","PRIM_TBLO","PRIM_TBLO.Column","PRIM_TBLO.Row","PRIM_LIST","PRIM_TBLO.Item","PRIM_LIST.Image","PRIM_LIST.String","PRIM_LIST.Button","PRIM_WEB.ResourceRequest"]
});