LANSA.addComponent({id:"XDEMOW_73",nm:"xDemoWebPaginatedList",ot:"wp",tp:"Web Page",de:"Paginated List",tl:14010003},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")||(l.gCL()=="LLL")){cL=l.gCL();}var c1=l.cDec("1.87");var Fd={F1:{nm:"EMPTHM",ft:"BL",ln:0,dc:0,lb:{"ENG":"Employee Image","FRA":"Image","JPN":"???????","LLL":"Employee Image"}[cL],h1:{"ENG":"Employee","FRA":"Image","JPN":"社員ｲﾒｰｼﾞ","LLL":"Employee"}[cL],h2:{"ENG":"Image","FRA":" ","JPN":" ","LLL":"Image"}[cL],h3:" ",
de:{"ENG":"Employee Image Thumbnail","FRA":"Image","JPN":"社員ｲﾒｰｼﾞ","LLL":"Employee Image"}[cL],dv:l.SqlNull,ia:["ASQN","FE","LC"]},F2:{nm:"EMPNO",ft:"A",ln:5,dc:0,lb:{"ENG":"Employee no....","FRA":"No employé  . .","JPN":"Employee no....","LLL":"Employee no...."}[cL],h1:{"ENG":"  Employ","FRA":"Salarié","JPN":"  Employ","LLL":"  Employ"}[cL],h2:{"ENG":"  Number","FRA":" ","JPN":"  Number","LLL":"  Number"}[cL],h3:" ",de:{"ENG":"Employee Number","FRA":"Numéro d´employé","JPN":"Employee Number","LLL":"Employee Number"}[cL],
dv:"",ia:["FE"]},F3:{nm:"SURNAME",ft:"A",ln:20,dc:0,ks:"O",lb:"Surname........",h1:"Surname",h2:"",h3:"",de:"Employee Surname",dv:"",ia:["FE","LC"]},F4:{nm:"GIVENAME",ft:"A",ln:20,dc:0,ks:"O",lb:"Given names....",h1:"Given name(s)",h2:"",h3:"",de:"Employee Given Name(s)",dv:"",ia:["FE","LC"]},F5:{nm:"ADDRESS1",ft:"A",ln:25,dc:0,lb:{"ENG":"Address 1......","FRA":"Adresse 1 . . .","JPN":"Address 1......","LLL":"Address 1......"}[cL],h1:{"ENG":"Address line 1","FRA":"Adresse ligne 1","JPN":"Address line 1","LLL":"Address line 1"}[cL],
h2:" ",h3:" ",de:{"ENG":"Street No and Name","FRA":"Adresse ligne 1","JPN":"Street No and Name","LLL":"Street No and Name"}[cL],dv:"",ia:["FE","LC"]},F6:{nm:"ADDRESS2",ft:"A",ln:25,dc:0,ks:"O",lb:{"ENG":"Address 2......","FRA":"Adresse 2 . . .","JPN":"Address 2......","LLL":"Address 2......"}[cL],h1:{"ENG":"Address line 2","FRA":"Adresse ligne 2","JPN":"Address line 2","LLL":"Address line 2"}[cL],h2:" ",h3:" ",de:{"ENG":"Suburb or Town","FRA":"Adresse ligne 2","JPN":"Suburb or Town","LLL":"Suburb or Town"}[cL],
dv:"",ia:["FE","LC"]},F7:{nm:"ADDRESS3",ft:"A",ln:25,dc:0,ks:"O",lb:{"ENG":"Country","FRA":"Adresse 3 . . .","JPN":"Country","LLL":"Country"}[cL],h1:{"ENG":"Country","FRA":"Adresse ligne 3","JPN":"Country","LLL":"Country"}[cL],h2:" ",h3:" ",de:{"ENG":"State and Country","FRA":"Adresse ligne 3","JPN":"State and Country","LLL":"State and Country"}[cL],dv:"",ia:["FE","LC"]},F8:{nm:"POSTCODE",ft:"S",ln:6,dc:0,ec:"3",lb:{"ENG":"Post/zip code..","FRA":"Code postal . .","JPN":"Post/zip code..","LLL":"Post/zip code.."}[cL],
h1:{"ENG":"Post/zip","FRA":"Code","JPN":"Post/zip","LLL":"Post/zip"}[cL],h2:{"ENG":"Code","FRA":"Postal","JPN":"Code","LLL":"Code"}[cL],h3:" ",de:{"ENG":"Post / Zip Code","FRA":"Code postal","JPN":"Post / Zip Code","LLL":"Post / Zip Code"}[cL],dv:0,ia:["FE"]}};var cO=l.rC(oI,{an:"PRIM_WEB",fd:Fd,mt:{Load:{},ShowPage:{ps:{"Page":{pt:"i"}}}},co:function(){cO.aN.call(this);var f=this.aF("XDEMOW_73",Fd);var C0=this.cR("TABLELAYOUT1","PRIM_TBLO");var C1=this.cR("COLUMN1","PRIM_TBLO","Column");var C2=this.cR("ROW1","PRIM_TBLO","Row");
var C3=this.cR("ROW2","PRIM_TBLO","Row");var C4=this.cR("LAYOUTITEM1","PRIM_TBLO","Item");var C5=this.cR("LAYOUTITEM2","PRIM_TBLO","Item");var C6=this.cR("LAYOUTITEM3","PRIM_TBLO","Item");var C7=this.cR("LAYOUTITEM4","PRIM_TBLO","Item");var C8=this.cR("LIST","PRIM_LIST");var C9=this.cR("COLUMNEMPTHM1","PRIM_LIST","Image");var C10=this.cR("COLUMNEMPNO1","PRIM_LIST","String");var C11=this.cR("COLUMNSURNAME1","PRIM_LIST","String");var C12=this.cR("COLUMNGIVENAME1","PRIM_LIST","String");var C13=this.cR("COLUMNXDEMOW_61","PRIM_LIST","Part");
var C14=this.cR("CURRENTPAGE","PRIM_SPDT");var C15=this.cR("LABEL1","PRIM_LABL");var C16=this.cR("OFPAGES","PRIM_LABL");C0.iC();C1.setDisplayPosition(1);C1.setParent(C0);C1.iC();C2.setDisplayPosition(1);C2.setParent(C0);C2.setHeight(52);C2.setUnits("PIXELS");C2.iC();C3.setDisplayPosition(2);C3.setParent(C0);C3.setHeight(c1);C3.iC();C4.setColumn(C1);C4.setManage(C8);C4.setParent(C0);C4.setRow(C3);C4.iC();C5.setAlignment("CENTERLEFT");C5.setColumn(C1);C5.setFlow("RIGHT");C5.setManage(C14);C5.setParent(C0);
C5.setRow(C2);C5.setSizing("NONE");C5.iC();C6.setAlignment("CENTERLEFT");C6.setColumn(C1);C6.setFlow("RIGHT");C6.setManage(C15);C6.setParent(C0);C6.setRow(C2);C6.setSizing("NONE");C6.setMarginLeft(4);C6.iC();C7.setAlignment("CENTERLEFT");C7.setColumn(C1);C7.setFlow("RIGHT");C7.setManage(C16);C7.setParent(C0);C7.setRow(C2);C7.setSizing("NONE");C7.setMarginLeft(2);C7.iC();C8.setDisplayPosition(2);C8.setHeight(748);C8.setLeft(0);C8.setParent(this);C8.setTabPosition(1);C8.setTop(52);C8.setWidth(1200);
C8.setRowHeight(40);C8.setColumnLines(false);C8.setRowLines(false);C8.iC();C9.setDisplayPosition(1);C9.setParent(C8);C9.setSource(f.F1);C9.setColumnWidth(43);C9.setCellMarginBottom(2);C9.setCellMarginLeft(2);C9.setCellMarginRight(2);C9.setCellMarginTop(2);C9.setImageSizing("BESTFIT");C9.iC();C10.setDisplayPosition(2);C10.setParent(C8);C10.setSource(f.F2);C10.iC();C11.setDisplayPosition(3);C11.setParent(C8);C11.setSource(f.F3);C11.setColumnWidth(190);C11.iC();C12.setDisplayPosition(4);C12.setParent(C8);
C12.setSource(f.F4);C12.setColumnWidth(222);C12.iC();C13.setColumnWidth(184);C13.setDesign("XDEMOW_6");C13.setDisplayPosition(5);C13.setParent(C8);C13.setColumnCaption("Address");C13.iC();C14.setDisplayPosition(3);C14.setLeft(45);C14.setParent(this);C14.setShowSelection(false);C14.setShowSelectionHilight(false);C14.setTabPosition(2);C14.setTop(14);C14.setWidth(64);C14.setDisplayAlignment("RIGHT");C14.setEditAlignment("RIGHT");C14.iC();C15.setCaption("Page ");C15.setDisplayPosition(1);C15.setEllipses("WORD");
C15.setHeight(25);C15.setLeft(4);C15.setParent(this);C15.setTabPosition(4);C15.setTabStop(false);C15.setTop(14);C15.setVerticalAlignment("CENTER");C15.setWidth(41);C15.iC();C16.setCaption("of 80");C16.setDisplayPosition(4);C16.setEllipses("WORD");C16.setHeight(25);C16.setLeft(111);C16.setParent(this);C16.setTabPosition(3);C16.setTabStop(false);C16.setTop(14);C16.setVerticalAlignment("CENTER");C16.setWidth(120);C16.iC();C14.aH("CHANGED",this,e3);C13.aLF({"ADDRESS1":f.F5,"ADDRESS2":f.F6,"ADDRESS3":f.F7,"POSTCODE":f.F8});
this.setLayoutManager(C0);this.aH("CREATEINSTANCE",this,e1);var li=this.aL("XDEMOW_73");li.EMPLOYEES=l.cLT({"EMPTHM":f.F1,"EMPNO":f.F2,"GIVENAME":f.F4,"SURNAME":f.F3,"ADDRESS1":f.F5,"ADDRESS2":f.F6,"ADDRESS3":f.F7,"POSTCODE":f.F8},null);li.DATA=l.cLT({"EMPTHM":f.F1,"EMPNO":f.F2,"GIVENAME":f.F4,"SURNAME":f.F3,"ADDRESS1":f.F5,"ADDRESS2":f.F6,"ADDRESS3":f.F7,"POSTCODE":f.F8},null);}});function e1(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Com_owner.Createinstance",25);r.ln=25;{r.ln=27;m.CURRENTPAGE.set(1);
r.ln=29;this.mthLOAD();}r.ln=31;r.e();};cO.mthLOAD=function(){var li=this.LIST.XDEMOW_73,r=l.mR(this,cO,"Load",33);var C0=r.cDR("GETEMPLOYEES","XDEMODATA","GETEMPLOYEES");C0.iC();C0.aH("COMPLETED",this,e2);r.ln=33;{r.ln=37;C0.mthEXECUTEASYNC({},{LIST:{"EMPLOYEES":li.EMPLOYEES}});}r.ln=54;r.e();function e2(sender,Ps){var r=l.eR(this,cO,"#GetEmployees.Completed",39);r.ln=39;{r.ln=42;for(var i1=1,s1=1,t1=30;(((s1>=0)&&(i1<=t1))||((s1<0)&&(i1>=t1)));i1+=s1){r.ln=44;for(var i2=1;i2<=li.EMPLOYEES.entryCount();i2++)
{li.EMPLOYEES.getEntry(i2);r.ln=45;li.DATA.addEntry();}}r.ln=50;cO.mthSHOWPAGE.call(this,1);}r.ln=52;r.e();}};function e3(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#CurrentPage.Changed",56);r.ln=56;{r.ln=58;m.CURRENTPAGE.set(l.n.Bound(m.CURRENTPAGE.getValue(),1,80));r.ln=60;cO.mthSHOWPAGE.call(this,m.CURRENTPAGE.get());}r.ln=62;r.e();};cO.mthSHOWPAGE=function(p0){var li=this.LIST.XDEMOW_73,m=this.REF,r=l.mR(this,cO,"ShowPage",64);var P0=r.cP("PAGE","PRIM_NMBR");P0.set(p0);var C0=r.cR("CURRENTITEM","PRIM_NMBR");
C0.iC();r.ln=64;{r.ln=69;m.LIST.clearList();r.ln=71;for(var i1=1;i1<=li.DATA.entryCount();i1++){li.DATA.getEntry(i1);r.ln=73;C0.set(l.add(C0.get(),1));r.ln=75;if(l.tB(l.n.le(C0.get(),l.mul(l.sub(P0.get(),1),15)))){continue;}r.ln=77;m.LIST.addEntry();r.ln=79;if(l.tB(l.n.gt(C0.get(),l.mul(P0.get(),15)))){break;}}}r.ln=83;r.e();};},{rp:["PRIM_WEB","PRIM_TBLO","PRIM_TBLO.Column","PRIM_TBLO.Row","PRIM_TBLO.Item","PRIM_LIST","PRIM_LIST.Image","PRIM_LIST.String","PRIM_LIST.Part","PRIM_SPDT","PRIM_LABL","PRIM_WEB.DataRequest"],
dp:["PRIM_NMBR"]});