LANSA.addComponent({id:"XKMLOGIN",nm:"XKMLogin",ot:"rp",tp:"Reusable Part",de:"Login",tl:14010000},function(l,oI,u){var cO=l.rC(oI,{an:"PRIM_PPNL",pt:{User:{da:"na"}},mt:{Login:{},Logout:{}},co:function(){cO.aN.call(this);var C0=this.cR("STYLE1","PRIM_VS","Style");var C1=this.cR("BRUSH1","PRIM_VS","SolidBrush");var C2=this.cR("STYLE2","PRIM_VS","Style");var C3=this.cR("BRUSH2","PRIM_VS","SolidBrush");var C4=this.cR("TABLELAYOUT1","PRIM_TBLO");var C5=this.cR("COLUMN1","PRIM_TBLO","Column");var C6=this.cR("ROW1","PRIM_TBLO","Row");
var C7=this.cR("LAYOUTITEM1","PRIM_TBLO","Item");var C8=this.cR("LAYOUTITEM2","PRIM_TBLO","Item");var C9=this.cR("LAYOUTITEM3","PRIM_TBLO","Item");var C10=this.cR("LAYOUTITEM4","PRIM_TBLO","Item");var C11=this.cR("LAYOUTITEM5","PRIM_TBLO","Item");var C12=this.cR("EDIT_USER","PRIM_EDIT");var C13=this.cR("EDIT_PASSWORD","PRIM_EDIT");var C14=this.cR("LABEL_INVALID","PRIM_LABL");var C15=this.cR("LOGIN","PRIM_PHBN");var C16=this.cR("LABEL_HINT","PRIM_LABL");var C17=this.cA("APPLICATION","XKMAPP");C0.setBackgroundBrush(C1);
C0.iC();C1.setColor("0:0:0");C1.setOpacity(20);C1.iC();C2.setForegroundBrush(C3);C2.setItalic(true);C2.iC();C3.setColor("255:21:3");C3.iC();C4.iC();C5.setDisplayPosition(1);C5.setParent(C4);C5.iC();C6.setDisplayPosition(1);C6.setParent(C4);C6.iC();C7.setColumn(C5);C7.setFlow("RIGHT");C7.setManage(C15);C7.setParent(C4);C7.setRow(C6);C7.setSizing("NONE");C7.setAlignment("BOTTOMRIGHT");C7.setMarginBottom(10);C7.setMarginRight(10);C7.iC();C8.setAlignment("TOPCENTER");C8.setColumn(C5);C8.setFlow("DOWN");
C8.setManage(C12);C8.setParent(C4);C8.setRow(C6);C8.setSizing("FITTOWIDTH");C8.setMarginTop(10);C8.setMarginLeft(10);C8.setMarginRight(10);C8.iC();C9.setAlignment("TOPCENTER");C9.setColumn(C5);C9.setFlow("DOWN");C9.setManage(C13);C9.setParent(C4);C9.setRow(C6);C9.setSizing("FITTOWIDTH");C9.setMarginTop(10);C9.setMarginLeft(10);C9.setMarginRight(10);C9.iC();C10.setColumn(C5);C10.setManage(C14);C10.setParent(C4);C10.setRow(C6);C10.setSizing("FITTOWIDTH");C10.setAlignment("TOPCENTER");C10.setFlow("DOWN");
C10.setMarginLeft(10);C10.setMarginRight(10);C10.iC();C11.setColumn(C5);C11.setManage(C16);C11.setParent(C4);C11.setRow(C6);C11.setSizing("FITTOWIDTH");C11.setAlignment("TOPCENTER");C11.setFlow("DOWN");C11.setMarginTop(10);C11.setMarginLeft(10);C11.setMarginRight(10);C11.iC();C12.setDisplayPosition(3);C12.setParent(this);C12.setShowSelection(false);C12.setShowSelectionHilight(false);C12.setTabPosition(1);C12.setTop(40);C12.setWidth(235);C12.setHeight(40);C12.setPlaceholder("User");C12.iC();C13.setDisplayPosition(4);
C13.setParent(this);C13.setShowSelection(false);C13.setShowSelectionHilight(false);C13.setTabPosition(3);C13.setTop(90);C13.setWidth(235);C13.setHeight(40);C13.setPlaceholder("Password");C13.setPasswordChar("*");C13.iC();C14.setCaption("Invalid user or password");C14.setDisplayPosition(6);C14.setEllipses("WORD");C14.setHeight(25);C14.setParent(this);C14.setTabPosition(4);C14.setTabStop(false);C14.setTop(140);C14.setVerticalAlignment("CENTER");C14.setWidth(235);C14.setStyle(C2);C14.setVisible(false);
C14.iC();C15.setCaption("Login");C15.setDisplayPosition(2);C15.setLeft(130);C15.setParent(this);C15.setTabPosition(5);C15.setTop(190);C15.setHeight(47);C15.setWidth(115);C15.iC();C16.setCaption("Hint: User1 Password1");C16.setDisplayPosition(5);C16.setEllipses("WORD");C16.setHeight(25);C16.setParent(this);C16.setTabPosition(4);C16.setTabStop(false);C16.setTop(140);C16.setVerticalAlignment("CENTER");C16.setWidth(235);C16.setStyle(C2);C16.iC();if((C17!=null)&&(C17.iI()==false)){C17.iC();}C12.aH("CHANGED",this,e4);
C13.aH("CHANGED",this,e5);C15.aH("CLICK",this,e1);C17.aH("LOGGEDIN",this,e2);C17.aH("INVALIDLOGIN",this,e3);this.setHeight(249);this.setLeft(0);this.setTop(0);this.setWidth(257);this.setShroudStyle(C0);this.setCloseButton(true);this.setLayoutManager(C4);this.setTitleBar(true);this.setCaption("Login");this.setAutoFocus(true);this.setAutoClose(false);}});cO.mthGETUSER=function(){var m=this.REF,r=l.pR(this,cO,"GetUser",30);var P0=r.cP("USER","PRIM_ALPH");r.ln=30;{r.ln=33;P0.set(m.EDIT_USER.get());}r.ln=35;
return r.rV(P0.get());};function e1(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Login.Click",38);r.ln=38;{r.ln=40;m.APPLICATION.ref.mthLOGIN(m.EDIT_USER.get(),m.EDIT_PASSWORD.get());}r.ln=42;r.e();};cO.mthLOGIN=function(){var m=this.REF,r=l.mR(this,cO,"Login",44);r.ln=44;{r.ln=46;m.EDIT_USER.setValue("");r.ln=47;m.EDIT_PASSWORD.setValue("");r.ln=48;m.LABEL_INVALID.setVisible(false);r.ln=50;this.mthSHOWPOPUP(u,u,"CENTER",u,u);}r.ln=52;r.e();};cO.mthLOGOUT=function(){var m=this.REF,r=l.mR(this,cO,"Logout",54);
r.ln=54;{r.ln=56;m.APPLICATION.ref.mthLOGOUT();}r.ln=58;r.e();};function e2(sender,Ps){var r=l.eR(this,cO,"#Application.LoggedIn",60);r.ln=60;{r.ln=62;this.mthCLOSEPOPUP();}r.ln=64;r.e();};function e3(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Application.InvalidLogin",66);r.ln=66;{r.ln=68;m.LABEL_INVALID.setVisible(true);}r.ln=70;r.e();};function e4(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Edit_User.Changed",72);r.ln=72;{r.ln=74;m.LABEL_INVALID.setVisible(false);}r.ln=76;r.e();};function e5(sender,Ps)
{var m=this.REF,r=l.eR(this,cO,"#Edit_Password.Changed",78);r.ln=78;{r.ln=80;m.LABEL_INVALID.setVisible(false);}r.ln=82;r.e();};cO.getUSER=function(){return this.mthGETUSER();};},{rc:["XKMAPP"],rp:["PRIM_PPNL","PRIM_VS.Style","PRIM_VS.SolidBrush","PRIM_TBLO","PRIM_TBLO.Column","PRIM_TBLO.Row","PRIM_TBLO.Item","PRIM_EDIT","PRIM_LABL","PRIM_PHBN"]});