LANSA.addComponent({id:"DF_T54F1O",ot:"rp",tp:"Reusable Part",de:"\OC=List Manager Filter by Name",tl:14011102},function(l,oI,u){var lIO="";var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")){cL=l.gCL();}var Fd={F1:{nm:"DF_ELTX",ft:"A",ln:255,dc:0,lb:{"ENG":"Enter Text","FRA":"Texte","JPN":"ﾃｷｽﾄ"}[cL],h1:{"ENG":"Enter","FRA":"Texte","JPN":"ﾃｷｽﾄ"}[cL],h2:{"ENG":"Text","FRA":"Text","JPN":""}[cL],h3:"",de:{"ENG":"Enter Text","FRA":"Texte","JPN":"ﾃｷｽﾄ入力"}[cL],dv:"",ia:["LC","FE"]},F2:{nm:"STD_INT",ft:"I",
ln:4,dc:0,ec:"J",lb:{"ENG":"Std Integer","FRA":"?","JPN":"?"}[cL],h1:{"ENG":"Standard","FRA":"?","JPN":"?"}[cL],h2:{"ENG":"Integer","FRA":"?","JPN":"?"}[cL],h3:{"ENG":"Field","FRA":"?","JPN":"?"}[cL],de:{"ENG":"Standard Integer field","FRA":"?","JPN":"?"}[cL],dv:0,ia:["FE","RB"]},F3:{nm:"XSURNAME",ft:"N",ln:40,dc:0,lb:"Surname",h1:"Employee",h2:"Surname",h3:" ",de:"Surname",dv:"",ia:["FE","LC"]},F4:{nm:"XGIVENAME",ft:"N",ln:40,dc:0,lb:"Given Names",h1:"Employee",h2:"Given",h3:"Names",de:"Given Names",
dv:"",ia:["FE","LC"]},F5:{nm:"LISTCOUNT",ft:"P",ln:7,dc:0,ec:"J",lb:{"ENG":"Entries .......","FRA":"Entrées . . . .","JPN":"Entries ......."}[cL],h1:{"ENG":"Number","FRA":"Nombre","JPN":"Number"}[cL],h2:{"ENG":"of Entrys","FRA":"d´Entrées","JPN":"of Entrys"}[cL],h3:" ",de:{"ENG":"Number of entries in a browse list","FRA":"Liste, nombre d´entrées ds liste BROWSE","JPN":"Number of entries in a browse list"}[cL],dv:0,ia:["FE","RB"]},F6:{nm:"XEMPLOYID",ft:"A",ln:10,dc:0,lb:"Employee Id",h1:"Employee",
h2:"Identification",h3:" ",de:"Identification",dv:"",ia:["FE"]},F7:{nm:"XSTREET",ft:"N",ln:40,dc:0,lb:"Street",h1:"Street",h2:" ",h3:" ",de:"Street",dv:"",ia:["FE","LC"]},F8:{nm:"XCITY",ft:"N",ln:40,dc:0,lb:"City",h1:"City",h2:" ",h3:" ",de:"City",dv:"",ia:["FE","LC"]},F9:{nm:"XSTATE",ft:"N",ln:40,dc:0,lb:"State",h1:"State",h2:" ",h3:" ",de:"State",dv:"",ia:["FE","LC"]},F10:{nm:"XPOSTCODE",ft:"A",ln:10,dc:0,lb:"Postal Code",h1:"Postal",h2:"Code",h3:" ",de:"Postal Code",dv:"",ia:["FE"]},F11:{nm:"XPHONEHME",
ft:"A",ln:15,dc:0,lb:"Home Phone",h1:"Home",h2:"Telephone",h3:" ",de:"Home Telephone",dv:"",ia:["FE"]},F12:{nm:"XPHONEBUS",ft:"A",ln:15,dc:0,lb:"Business Phone",h1:"Business",h2:"Telephone",h3:" ",de:"Business Telephone",dv:"",ia:["FE"]},F13:{nm:"XSTARTDTE",ft:"D",ln:10,dc:0,lb:"Start Date",h1:"Start",h2:"Date",h3:" ",de:"Start Date",dv:l.SqlNull,ia:["FE","ASQN"]},F14:{nm:"XTERMDATE",ft:"D",ln:10,dc:0,lb:"Termination",h1:"Termination",h2:"Date",h3:" ",de:"Termination Date",dv:l.SqlNull,ia:["FE","ASQN"]
},F15:{nm:"XDEPTMENT",ft:"A",ln:4,dc:0,lb:"Department",h1:"Department",h2:"Code",h3:" ",de:"Department",dv:"",ia:["FE"]},F16:{nm:"XSALARY",ft:"P",ln:15,dc:2,ec:"1",lb:"Annual Salary",h1:"Annual",h2:"Salary",h3:" ",de:"Annual Salary",dv:0,ia:["FE","RB"]},F17:{nm:"IO$STS",ft:"A",ln:2,dc:0,lb:{"ENG":"I/O status ....","FRA":"Statut I/O  . .","JPN":"I/O status ...."}[cL],h1:{"ENG":"I/O","FRA":"Statut","JPN":"I/O"}[cL],h2:{"ENG":"Status","FRA":"I/O","JPN":"Status"}[cL],h3:" ",de:{"ENG":"Data base I/O operation status code","FRA":"Code statut opération I/O","JPN":"Data base I/O operation status code"}[cL],
dv:"",ia:["FE"]}};var cO=l.rC(oI,{an:"VF_AC007O",fd:Fd,mt:{uSelectData:{}},co:function(){cO.aN.call(this);var f=this.aF("DF_T54F1O",Fd);var C0=this.cR("LABEL_HOW_IT_WORKS","PRIM_LABL");var C1=this.cR("LABEL_INSTRUCTION","PRIM_LABL");var C2=this.cF("SEARCHSURNAME",Fd.F1.VISUALEDIT);var C3=this.cR("BUTTON_SEARCH","PRIM_PHBN");C0.setCaption("See component DF_T54F1O for details of this FILTER");C0.setDisplayPosition(4);C0.setEllipses("WORD");C0.setHeight(57);C0.setLeft(8);C0.setParent(this);C0.setTabPosition(4);
C0.setTabStop(false);C0.setTop(3);C0.setVerticalAlignment("CENTER");C0.setWidth(177);C0.iC();C1.setCaption("Enter a partial surname");C1.setDisplayPosition(1);C1.setHeight(25);C1.setLeft(8);C1.setParent(this);C1.setTabPosition(1);C1.setTabStop(false);C1.setTop(62);C1.setWidth(193);C1.setVerticalAlignment("CENTER");C1.iC();C2.setDisplayPosition(2);C2.setHeight(25);C2.setParent(this);C2.setTabPosition(2);C2.setTop(94);C2.setWidth(145);C2.setLabelType("CAPTION");C2.setMarginLeft(0);C2.setLeft(8);C2.aD();
C2.iC();C3.setCaption("Search");C3.setDisplayPosition(3);C3.setHeight(33);C3.setParent(this);C3.setTabPosition(3);C3.setTop(126);C3.setWidth(145);C3.setLeft(8);C3.setEnabled(false);C3.iC();C2.aH("ENTER",this,e1);C2.aH("CHANGED",this,e2);C3.aH("CLICK",this,e1);this.setHeight(169);this.setWidth(193);this.setLayoutManager(null);var li=this.aL("DF_T54F1O");li.SAVE_KEYS=l.cLT({"XSURNAME":f.F3,"XGIVENAME":f.F4},null);li.XEMPLOYEELIST=l.cLT({"XEMPLOYID":f.F6,"XSURNAME":f.F3,"XGIVENAME":f.F4,"XSTREET":f.F7,"XCITY":f.F8,"XSTATE":f.F9,"XPOSTCODE":f.F10,"XPHONEHME":f.F11,"XPHONEBUS":f.F12,"XSTARTDTE":f.F13,"XTERMDATE":f.F14,"XDEPTMENT":f.F15,"XSALARY":f.F16},f.F5);
}});var cA=cO.aN.prototype;function e1(sender,Ps){var r=l.eR(this,cO,"#Button_Search.Click #SearchSurname.Enter",39);r.ln=39;{r.ln=41;this.mthUSELECTDATA();}r.ln=43;r.e();};function e2(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#SearchSurname.Changed",46);r.ln=46;{r.ln=48;m.BUTTON_SEARCH.setEnabled(l.s.ne(l.s.Trim(m.SEARCHSURNAME.get()),""));}r.ln=50;r.e();};cO.mthUSELECTDATA=function(){var li=this.LIST.DF_T54F1O,f=this.FLD.DF_T54F1O,m=this.REF,r=l.mR(this,cO,"uSelectData",53);var C0=r.cDR("FIND","DF_T54DSO","FINDEMPBYSURNAME");
C0.iC();C0.aH("COMPLETED",this,e3);r.ln=53;{r.ln=59;if(l.s.eq(l.s.Trim(m.SEARCHSURNAME.get()),"")){r.e();return;}r.ln=64;li.SAVE_KEYS.initList(1);r.ln=67;this.mthAVGOTOBUSYSTATE("Searching",false,u);r.ln=70;this.REF.AVLISTMANAGER.mthCLEARLIST(u);r.ln=73;C0.mthEXECUTEASYNC({FLD:{"XSURNAME":m.SEARCHSURNAME.get(),"XGIVENAME":f.F4.get()}},{LIST:{"XEMPLOYEELIST":li.XEMPLOYEELIST}});}r.ln=104;r.e();function e3(sender,Ps){var r=l.eR(this,cO,"#Find.Completed",76);var C1=r.cF("NUMERICPOSTALCODE",Fd.F2.Dc);
C1.iC();r.ln=76;{r.ln=81;{var l1=li.XEMPLOYEELIST.selectList();while(l1.step()){r.ln=85;if(l.s.IsNumber(f.F10.get())){r.ln=86;C1.set(l.s.AsNumber(f.F10.get()));}else{r.ln=88;C1.set(0);}r.ln=91;this.REF.AVLISTMANAGER.mthADDTOLIST(f.F6.get(),l.add(l.cat(f.F3.get(),", "),f.F4.get()),f.F6.get(),u,u,u,u,u,u,u,u,u,u,u,u,u,u,u,u,u,f.F12.get(),f.F7.get(),u,u,u,u,u,u,u,u,C1.get(),u,u,u,u,u,u,u,u,u,u,u,u,u,u,u,u);r.ln=93;}l1.end();}r.ln=96;f.F17.set(lIO=li.SAVE_KEYS.getEntry(1));r.ln=99;this.mthAVGOTOFREESTATE();
}r.ln=101;r.e();}};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);};l.cFC({co:Fd.F1.Dc,an:"PRIM_FLD",fn:"DF_ELTX"});Fd.F1.VISUALEDIT=function(){this.aN.call(this,new Fd.F1.Dc());this.setComponentVersion(1);this.setHeight(21);this.setUsePicklist(false);this.setWidth(782);};l.cFC({co:Fd.F1.VISUALEDIT,an:"PRIM_EVEF",fn:"DF_ELTX",cn:"VisualEdit"});}{Fd.F2.Dc=function(){this.aN.call(this,Fd.F2);};l.cFC({co:Fd.F2.Dc,an:"PRIM_FLD",fn:"STD_INT"});}cO.srAVLISTMANAGER=function(rn){cA.srAVLISTMANAGER.call(this,rn);
};},{rc:["VF_AC007O"],rp:["PRIM_LABL","PRIM_EVEF","PRIM_PHBN","PRIM_WEB.DataRequest","PRIM_FLD"]});