LANSA.addComponent({id:"DF_T2802O",ot:"rp",tp:"Reusable Part",de:"\OC=SubType Example Handler",tl:14011102},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")){cL=l.gCL();}var Fd={F1:{nm:"STD_TEXTL",ft:"A",ln:75,dc:0,lb:"Text",h1:"Text",h2:" ",h3:" ",de:{"ENG":"Standard TEXT, LONG","FRA":"Texte Long Standard","JPN":"Standard TEXT, LONG"}[cL],dv:"",ia:["LC"]},F2:{nm:"STD_OBJ",ft:"A",ln:10,dc:0,lb:{"ENG":"Object Name","FRA":"Nom d´Objet","JPN":"Object Name"}[cL],h1:{"ENG":"Object","FRA":"Nom","JPN":"Object"}[cL],
h2:{"ENG":"Name","FRA":"Objet","JPN":"Name"}[cL],h3:" ",de:{"ENG":"Standard OBJECT NAME (S/38 or AS/400)","FRA":"Nom d´Objet Standard (S/38 ou AS/400)","JPN":"Standard OBJECT NAME (S/38 or AS/400)"}[cL],dv:"",ia:["VN"]},F3:{nm:"STD_TEXTS",ft:"A",ln:30,dc:0,lb:{"ENG":"Text","FRA":"Texte","JPN":"Text"}[cL],h1:{"ENG":"Text","FRA":"Texte","JPN":"Text"}[cL],h2:" ",h3:" ",de:{"ENG":"Standard TEXT, SHORT","FRA":"Texte Court Standard","JPN":"Standard TEXT, SHORT"}[cL],dv:"",ia:["LC"]}};var cO=l.rC(oI,{an:"VF_AC010O",
fd:Fd,mt:{uInitialize:{},uExecute:{ps:{"GotoFreeState":{pt:"io"},"SwitchCallerReference":{pt:"i"}}},PrependArrow:{ps:{"To":{pt:"i"}}}},co:function(){cO.aN.call(this);this.aF("DF_T2802O",Fd);var C0=this.cR("THISDEMOOBJECT","PRIM_LABL");var C1=this.cR("THISDEMOOBJECTSTYLE","PRIM_VS","Style");var C2=this.cF("STD_TEXTL",Fd.F1.VISUAL);var C3=this.cF("STD_OBJ",Fd.F2.VISUAL);var C4=this.cF("STD_TEXTS",Fd.F3.VISUAL);var C5=this.cR("LABL_1","PRIM_LABL");var C6=this.cR("LABL_2","PRIM_LABL");var C7=this.cR("LABL_3","PRIM_LABL");
var C8=this.cR("LABL_4","PRIM_LABL");var C9=this.cR("STYLEBLUE","PRIM_VS","Style");C0.setParent(this);C0.setDisplayPosition(3);C0.setTabPosition(3);C0.setTabStop(false);C0.setHeight(23);C0.setWidth(677);C0.setCaption("DF_T2802O - Switch and Signal 1");C0.setStyle(C1);C0.setTop(4);C0.setLeft(25);C0.iC();C1.setTextColor("BLUE");C1.setFontSize(14);C1.iC();C2.setCaption("Account Holder");C2.setDisplayPosition(1);C2.setHeight(19);C2.setLabelType("CAPTION");C2.setLeft(76);C2.setParent(this);C2.setReadOnly(true);
C2.setTabPosition(1);C2.setTop(142);C2.setUsePicklist(false);C2.setWidth(325);C2.setStyle(C9);C2.setMarginLeft(170);C2.aD();C2.iC();C3.setCaption("Account Number");C3.setDisplayPosition(2);C3.setHeight(19);C3.setLabelType("CAPTION");C3.setLeft(76);C3.setParent(this);C3.setReadOnly(true);C3.setTabPosition(2);C3.setTop(163);C3.setUsePicklist(false);C3.setWidth(325);C3.setStyle(C9);C3.setMarginLeft(170);C3.aD();C3.iC();C4.setCaption("Business Object SubType");C4.setDisplayPosition(4);C4.setHeight(19);
C4.setLabelType("CAPTION");C4.setLeft(76);C4.setParent(this);C4.setReadOnly(true);C4.setTabPosition(4);C4.setTop(187);C4.setUsePicklist(false);C4.setWidth(325);C4.setStyle(C9);C4.setMarginLeft(170);C4.aD();C4.iC();C5.setCaption("This example uses an ACCOUNT business object. An ACCOUNT has 3 SubTypes identified as SAV (Savings), CHK (Check) and INV (Investment) :");C5.setDisplayPosition(8);C5.setHeight(39);C5.setLeft(24);C5.setParent(this);C5.setTabPosition(8);C5.setTabStop(false);C5.setWidth(585);
C5.setTop(34);C5.iC();C6.setCaption("SAV (Saving) subtype instances should only enable tabs Details, Charges and History.");C6.setDisplayPosition(7);C6.setHeight(25);C6.setLeft(48);C6.setParent(this);C6.setTabPosition(7);C6.setTabStop(false);C6.setTop(72);C6.setWidth(705);C6.iC();C7.setCaption("CHK (Check) subtype instances should only enable tabs Details, Approve, Dates, History and Transactions.");C7.setDisplayPosition(6);C7.setHeight(25);C7.setLeft(46);C7.setParent(this);C7.setTabPosition(6);C7.setTabStop(false);
C7.setTop(93);C7.setWidth(707);C7.iC();C8.setCaption("INV (Investment) subtype instances should only enable tabs Details, History, Schedule and Transactions.");C8.setDisplayPosition(5);C8.setHeight(25);C8.setLeft(48);C8.setParent(this);C8.setTabPosition(5);C8.setTabStop(false);C8.setTop(112);C8.setWidth(705);C8.iC();C9.setTextColor("BLUE");C9.iC();this.setHeight(242);this.setWidth(769);}});var cA=cO.aN.prototype;cO.mthUINITIALIZE=function(){var m=this.REF,r=l.mR(this,cO,"uInitialize",36);r.ln=36;
{r.ln=38;m.LABL_2.setCaption(cO.mthPREPENDARROW.call(this,m.LABL_2.getCaption()));r.ln=39;m.LABL_3.setCaption(cO.mthPREPENDARROW.call(this,m.LABL_3.getCaption()));r.ln=40;m.LABL_4.setCaption(cO.mthPREPENDARROW.call(this,m.LABL_4.getCaption()));}r.ln=43;r.e();};cO.mthUEXECUTE=function(p0,p1){var m=this.REF,r=l.mR(this,cO,"uExecute",46);var P0=r.cP("GOTOFREESTATE","PRIM_BOLN");var P1=r.cPD("SWITCHCALLERREFERENCE");P0.set(p0.get());P1=p1;var C0=r.cD("C0");r.ln=46;{r.ln=50;cA.mthUEXECUTE.call(this,P0,P1);
r.ln=52;C0=r.sR("C0",this.REF.AVLISTMANAGER.getCURRENTINSTANCE());r.ln=54;m.THISDEMOOBJECT.setCaption(l.add("DF_T2802O - ",this.getAVCOMMANDCAPTION()));r.ln=56;if((C0==null)){r.ln=58;m.THISDEMOOBJECT.setCaption(l.add(m.THISDEMOOBJECT.getCaption(),l.cat(l.cat(l.add(" - ",C0.getAVVISUALID2().get())," - "),C0.getAVAKEY1().get())));r.ln=61;m.STD_OBJ.set("Not Available");r.ln=62;m.STD_TEXTL.set("Not Available");r.ln=63;m.STD_TEXTS.set("Not Available");}else{r.ln=67;m.STD_OBJ.set(C0.getAVAKEY1().get());
r.ln=68;m.STD_TEXTL.set(l.s.AsNativeString(C0.getAVVISUALID2().get()));r.ln=69;m.STD_TEXTS.set(C0.getAVSUBTYPE().get());}p0.set(P0.get());}r.ln=73;r.e();};cO.mthPREPENDARROW=function(p0){var r=l.mR(this,cO,"PrependArrow",76);var P0=r.cP("TO","PRIM_DC","UnicodeString");var P1=r.cP("RESULT","PRIM_DC","UnicodeString");P0.set(p0);r.ln=76;{r.ln=79;P1.set(l.add(l.cat(l.n.AsUnicodeString(8680)," "),P0.get()));}r.ln=80;return r.rV(P1.get());};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);};l.cFC({co:Fd.F1.Dc,an:"PRIM_FLD",fn:"STD_TEXTL"});
Fd.F1.VISUAL=function(){this.aN.call(this,new Fd.F1.Dc());};l.cFC({co:Fd.F1.VISUAL,an:"PRIM_EVEF",fn:"STD_TEXTL",cn:"Visual"});}{Fd.F2.Dc=function(){this.aN.call(this,Fd.F2);};l.cFC({co:Fd.F2.Dc,an:"PRIM_FLD",fn:"STD_OBJ"});Fd.F2.VISUAL=function(){this.aN.call(this,new Fd.F2.Dc());};l.cFC({co:Fd.F2.VISUAL,an:"PRIM_EVEF",fn:"STD_OBJ",cn:"Visual"});}{Fd.F3.Dc=function(){this.aN.call(this,Fd.F3);};l.cFC({co:Fd.F3.Dc,an:"PRIM_FLD",fn:"STD_TEXTS"});Fd.F3.VISUAL=function(){this.aN.call(this,new Fd.F3.Dc());
};l.cFC({co:Fd.F3.VISUAL,an:"PRIM_EVEF",fn:"STD_TEXTS",cn:"Visual"});}cO.srAVLISTMANAGER=function(rn){cA.srAVLISTMANAGER.call(this,rn);};},{rc:["VF_AC010O"],rp:["PRIM_LABL","PRIM_VS.Style","PRIM_EVEF"],dc:["VF_LM003O"]});