LANSA.addComponent({id:"VF_UI008O",ot:"rp",tp:"Reusable Part",de:"\OC=Pop up Menu",tl:14011102},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")){cL=l.gCL();}var Fd={F1:{nm:"STD_INT",ft:"I",ln:4,dc:0,ec:"J",lb:{"ENG":"Std Integer","FRA":"?","JPN":"?"}[cL],h1:{"ENG":"Standard","FRA":"?","JPN":"?"}[cL],h2:{"ENG":"Integer","FRA":"?","JPN":"?"}[cL],h3:{"ENG":"Field","FRA":"?","JPN":"?"}[cL],de:{"ENG":"Standard Integer field","FRA":"?","JPN":"?"}[cL],dv:0,ia:["FE","RB"]},F2:{nm:"VF_ELIDN",
ft:"A",ln:32,dc:0,lb:{"ENG":"Internal Identi","FRA":"Standard Identi","JPN":"Standard Identi"}[cL],h1:{"ENG":"Internal","FRA":"Standard","JPN":"Standard"}[cL],h2:"Identifier",h3:"",de:{"ENG":"Internal Identifier","FRA":"Standard Identifier","JPN":"Standard Identifier"}[cL],dv:"",ia:["FE"]},F3:{nm:"VF_ELSYMN",ft:"A",ln:50,dc:0,lb:"Image Name",h1:"Image",h2:"Name",h3:"",de:"Image Name",dv:"",ia:["FE"]},F4:{nm:"VF_ELSTAT",ft:"A",ln:1,dc:0,lb:"Standard Char 1",h1:"Standard",h2:"Char",h3:"1",de:"Standard Char 1 State Flag",
dv:"",ia:["FE"]}};var cO=l.rC(oI,{an:"PRIM_OBJT",fd:Fd,pt:{MenuItemsCollection:{da:"r"}},mt:{uInitialize:{ps:{"UseWidth":{pt:"i"}}},uTerminate:{},uAlterTextandEvent:{ps:{"OfMenuItem":{pt:"i"},"ToEventName":{pt:"i"},"ToText":{pt:"i"}}},AddMenuItem:{ps:{"Text":{pt:"i"},"EventName":{pt:"i"},"UseOptionalImageName":{pt:"i"},"UseOptionalImageSource":{pt:"i"},"AssociatedReference":{pt:"i"},"Enabled":{pt:"i"}}},uShow:{}},ev:{ItemSelected:{ps:{"EventName":{pt:"i"},"AssociatedReference":{pt:"i"},"MenuItem":
{pt:"i"}}},Closing:{}},co:function(){cO.aN.call(this);this.aF("VF_UI008O",Fd);var C0=this.cA("USYSTEM","VF_SY001O");var C1=this.cR("MAINPOPUPMENU","PRIM_PPNL","Menu");var C2=this.cR("MENUITEMSCOLLECTION","PRIM_ACOL");var C3=this.cR("ASSOCIATEDREFERENCESCOLLECTION","PRIM_ACOL");var C4=this.cR("ASSOCIATEDEVENTSCOLLECTION","PRIM_ACOL");if((C0!=null)&&(C0.iI()==false)){C0.iC();}C1.iC();C2.setCollects("PRIM_PPNL.MenuItem");C2.iC();C3.setCollects("PRIM_OBJT");C3.iC();C4.setCollects("VF_ELIDN");C4.iC();
C0.aH("CURRENTTHEMEALTERED",this,e1);C1.aH("CLOSING",this,e3);C2.aH("CLICK",this,e2);}});cO.mthUINITIALIZE=function(p0){var m=this.REF,r=l.mR(this,cO,"uInitialize",28);var P0=r.cPF("USEWIDTH",Fd.F1.Dc);P0.set((p0===u)?(0):(p0));r.ln=28;{r.ln=31;m.USYSTEM.ref.mthAPPLYAPPROPRIATEEFFECTS(m.MAINPOPUPMENU);r.ln=33;if(l.n.gt(P0.get(),0)){r.ln=34;m.MAINPOPUPMENU.setWidth(P0.get());}}r.ln=38;r.e();};function e1(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#USystem.CurrentThemeAltered",41);r.ln=41;{r.ln=43;m.USYSTEM.ref.mthAPPLYAPPROPRIATEEFFECTS(m.MAINPOPUPMENU);
}r.ln=45;r.e();};cO.mthUTERMINATE=function(){var m=this.REF,r=l.mR(this,cO,"uTerminate",48);r.ln=48;{r.ln=50;m.ASSOCIATEDREFERENCESCOLLECTION.mthREMOVEALL();r.ln=51;m.ASSOCIATEDEVENTSCOLLECTION.mthREMOVEALL();r.ln=52;m.MENUITEMSCOLLECTION.mthREMOVEALL();}r.ln=54;r.e();};cO.mthUALTERTEXTANDEVENT=function(p0,p1,p2){var m=this.REF,r=l.mR(this,cO,"uAlterTextandEvent",57);var P0=r.cPD("OFMENUITEM");var P1=r.cPF("TOEVENTNAME",Fd.F2.Dc);var P2=r.cP("TOTEXT","PRIM_DC","UnicodeString");P0=p0;P1.set(p1);P2.set(p2);
r.ln=57;{r.ln=62;P0.setCaption(P2.get());r.ln=64;m.ASSOCIATEDEVENTSCOLLECTION.get(l.s.AsNumber(P0.getComponentTag())).set(P1.get());}r.ln=66;r.e();};function e2(MENUITEM,Ps){var m=this.REF,r=l.eR(this,cO,"#MenuItemsCollection<>.Click",69);var C0=r.cF("INDEX",Fd.F1.Dc);C0.iC();r.ln=69;{r.ln=73;if(MENUITEM.getEnabled()){r.ln=75;C0.set(l.s.AsNumber(MENUITEM.getComponentTag()));r.ln=77;{var eP=l.ePs();eP.cF("EVENTNAME",Fd.F2.Dc);eP.cD("ASSOCIATEDREFERENCE");eP.cD("MENUITEM");eP.r("EVENTNAME").set(m.ASSOCIATEDEVENTSCOLLECTION.get(C0.get()).get());
eP.sR("ASSOCIATEDREFERENCE",m.ASSOCIATEDREFERENCESCOLLECTION.get(C0.get()));eP.sR("MENUITEM",MENUITEM);this.fE("ITEMSELECTED",eP);eP.e();}}}r.ln=81;r.e();};function e3(sender,Ps){var r=l.eR(this,cO,"#MainPopupMenu.Closing",84);r.ln=84;{r.ln=86;this.fE("CLOSING");}r.ln=88;r.e();};cO.mthADDMENUITEM=function(p0,p1,p2,p3,p4,p5){var m=this.REF,r=l.mR(this,cO,"AddMenuItem",92);var P0=r.cP("TEXT","PRIM_DC","UnicodeString");var P1=r.cPF("EVENTNAME",Fd.F2.Dc);var P2=r.cPF("USEOPTIONALIMAGENAME",Fd.F3.Dc);
var P3=r.cPF("USEOPTIONALIMAGESOURCE",Fd.F4.Dc);var P4=r.cPD("ASSOCIATEDREFERENCE");var P5=r.cP("ENABLED","PRIM_BOLN");var P6=r.cPD("RETURNMENUITEM");P0.set(p0);P1.set(p1);P2.set(p2);P3.set(p3);P4=(p4===u)?(null):(p4);P5.set((p5===u)?(true):(p5));var C0=r.cR("MENUITEM","PRIM_PPNL","MenuItem");var C1=r.cF("INDEX",Fd.F1.Dc);C0.iC();C1.iC();r.ln=92;{r.ln=106;P6=r.sR("P6",C0);r.ln=108;m.MENUITEMSCOLLECTION.mthINSERT(C0);r.ln=109;m.ASSOCIATEDREFERENCESCOLLECTION.mthINSERT(P4);r.ln=110;m.ASSOCIATEDEVENTSCOLLECTION.mthINSERT(P1);
r.ln=112;C1.set(m.MENUITEMSCOLLECTION.getItemCount());r.ln=114;C0.setParent(m.MAINPOPUPMENU);C0.setCaption(P0.get());C0.setComponentTag(l.n.AsString(C1.get()));C0.setEnabled(P5.get());r.ln=116;C0.setImage(m.USYSTEM.ref.mthGETVLFIMAGEREFERENCE(P2.get(),"SMALL",P3.get(),false));r.ln=118;m.MAINPOPUPMENU.setHeight(l.add(l.mul(C1.get(),C0.getHeight()),3));}r.ln=121;return r.rR(P6);};cO.mthUSHOW=function(){var m=this.REF,r=l.mR(this,cO,"uShow",124);r.ln=124;{r.ln=126;m.MAINPOPUPMENU.mthSHOWPOPUP(u,u,u,u,u);
}r.ln=128;r.e();};cO.getMENUITEMSCOLLECTION=function(){return this.REF.MENUITEMSCOLLECTION;};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);};l.cFC({co:Fd.F1.Dc,an:"PRIM_FLD",fn:"STD_INT"});}{Fd.F2.Dc=function(){this.aN.call(this,Fd.F2);};l.cFC({co:Fd.F2.Dc,an:"PRIM_FLD",fn:"VF_ELIDN"});}{Fd.F3.Dc=function(){this.aN.call(this,Fd.F3);};l.cFC({co:Fd.F3.Dc,an:"PRIM_FLD",fn:"VF_ELSYMN"});}{Fd.F4.Dc=function(){this.aN.call(this,Fd.F4);};l.cFC({co:Fd.F4.Dc,an:"PRIM_FLD",fn:"VF_ELSTAT"});}},{rc:["VF_SY001O"],
rp:["PRIM_OBJT","PRIM_PPNL.Menu","PRIM_ACOL","PRIM_FLD"],dp:["PRIM_PPNL.MenuItem"]});