LANSA.addComponent({id:"XDEMOW_95",nm:"xDemoWebDesignsUDCTree",ot:"wp",tp:"Web Page",de:"Designs and UDC Trees",tl:14020000},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")||(l.gCL()=="LLL")){cL=l.gCL();}var c1=l.cDec("1.70");var Fd={F1:{nm:"XEMPLOYID",an:"xEmployeeIdentification",ft:"A",ln:10,dc:0,lb:"Employee Id",h1:"Employee",h2:"Identification",h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"Identification",dv:"",ia:["FE"]},F2:{nm:"XEMPTITLE",an:"xEmployeeTitle",ft:"N",
ln:40,dc:0,lb:"Title",h1:"Employee",h2:"Title",h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"Title",dv:"",ia:["FE","LC"]},F3:{nm:"XSURNAME",an:"xEmployeeSurname",ft:"N",ln:40,dc:0,lb:"Surname",h1:"Employee",h2:"Surname",h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"Surname",dv:"",ia:["FE","LC"]},F4:{nm:"XGIVENAME",an:"xEmployeeGivenNames",ft:"N",ln:40,dc:0,lb:"Given Names",h1:"Employee",h2:"Given",h3:"Names",de:"Given Names",dv:"",ia:["FE","LC"]},F5:{nm:"XEMPDOB",an:"xEmployeeDateofBirth",
ft:"D",ln:10,dc:0,lb:"Date of Birth",h1:"Employee",h2:"Birth Date",h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"Date of Birth",dv:l.SqlNull,ia:["ASQN","FE","ISO"]},F6:{nm:"XGENDER",an:"xEmployeeGender",ft:"A",ln:10,dc:0,lb:"Gender",h1:"Employee",h2:"Gender",h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"Gender",dv:"Male",ia:["FE","LC"]},F7:{nm:"XSTREET",an:"xEmployeeStreet",ft:"N",ln:40,dc:0,lb:"Street",h1:"Street",h2:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],
de:"Street",dv:"",ia:["FE","LC"]},F8:{nm:"XCITY",an:"xEmployeeCity",ft:"N",ln:40,dc:0,lb:"City",h1:"City",h2:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"City",dv:"",ia:["FE","LC"]},F9:{nm:"XSTATE",an:"xEmployeeState",ft:"N",ln:40,dc:0,lb:"State",h1:"State",h2:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"State",dv:"",ia:["FE","LC"]},F10:{nm:"XPOSTCODE",an:"xEmployeePostalCode",ft:"A",ln:10,dc:0,
lb:"Postal Code",h1:"Postal",h2:"Code",h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"Postal Code",dv:"",ia:["FE"]},F11:{nm:"XCOUNTRY",an:"xEmployeeCountry",ft:"N",ln:40,dc:0,lb:"Country",h1:"Country",h2:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"Country",dv:"",ia:["FE","LC"]},F12:{nm:"XPHONEHME",an:"xEmployeeHomeTelephone",ft:"A",ln:15,dc:0,lb:"Home Phone",h1:"Home",h2:"Telephone",h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"Home Telephone",
dv:"",ia:["FE"]},F13:{nm:"XPHONEBUS",an:"xEmployeeBusinessTelephone",ft:"A",ln:15,dc:0,lb:"Business Phone",h1:"Business",h2:"Telephone",h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"Business Telephone",dv:"",ia:["FE"]},F14:{nm:"XPHONEMOB",an:"xEmployeeMobilePhone",ft:"A",ln:15,dc:0,lb:"Mobile Phone",h1:"Employee",h2:"Mobile Phone",h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"Mobile Phone",dv:"",ia:["FE"]},F15:{nm:"XSALARY",an:"xEmployeeSalary",ft:"P",ln:15,dc:2,ec:"1",lb:"Annual Salary",
h1:"Annual",h2:"Salary",h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"Annual Salary",dv:0,ia:["FE","RB"]},F16:{nm:"XSTARTDTE",an:"xEmployeeStartDate",ft:"D",ln:10,dc:0,lb:"Start Date",h1:"Start",h2:"Date",h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"Start Date",dv:l.SqlNull,ia:["FE","ASQN"]},F17:{nm:"XTERMDATE",an:"xEmployeeTerminationDate",ft:"D",ln:10,dc:0,lb:"Termination",h1:"Termination",h2:"Date",h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"Termination Date",dv:l.SqlNull,
ia:["FE","ASQN"]},F18:{nm:"XDEPTMENT",an:"xDepartmentCode",ft:"A",ln:4,dc:0,lb:"Department",h1:"Department",h2:"Code",h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"Department",dv:"",ia:["FE"]},F19:{nm:"XEMPTHM",an:"xEmployeeImageThumbnail",ft:"BL",ln:0,dc:0,lb:{"ENG":"Employee Image","FRA":"Image","JPN":"Employee Image","LLL":"Employee Image"}[cL],h1:{"ENG":"Employee","FRA":"Image","JPN":"Employee","LLL":"Employee"}[cL],h2:{"ENG":"Image","FRA":" ","JPN":"Image","LLL":"Image"}[cL],h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],
de:{"ENG":"Employee Image Thumbnail","FRA":"Image","JPN":"Employee Image Thumbnail","LLL":"Employee Image Thumbnail"}[cL],dv:l.SqlNull,ia:["ASQN","FE","LC"]},F20:{nm:"XEMPIMG",an:"xEmployeeImage",ft:"BL",ln:0,dc:0,lb:{"ENG":"Employee Image","FRA":"Image","JPN":"Employee Image","LLL":"Employee Image"}[cL],h1:{"ENG":"Employee","FRA":"Image","JPN":"Employee","LLL":"Employee"}[cL],h2:{"ENG":"Image","FRA":" ","JPN":"Image","LLL":"Image"}[cL],h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:{"ENG":"Employee Image","FRA":"Image","JPN":"Employee Image","LLL":"Employee Image"}[cL],
dv:l.SqlNull,ia:["ASQN","FE","LC"]}};var cO=l.rC(oI,{an:"PRIM_WEB",fd:Fd,pt:{ActiveDesign:{da:"r"}},mt:{Load:{}},co:function(){cO.aN.call(this);var f=this.aF("XDEMOW_95",Fd);var C0=this.cR("DESIGNS","PRIM_DESN");var C1=this.cR("MOBILE","PRIM_DESN","Design");var C2=this.cR("LAYOUT","PRIM_TBLO");var C3=this.cR("LAYOUTROW1","PRIM_TBLO","Row");var C4=this.cR("LAYOUTCOLUMN1","PRIM_TBLO","Column");var C5=this.cR("ROW1","PRIM_TBLO","Row");var C6=this.cR("LAYOUTITEM1","PRIM_TBLO","Item");var C7=this.cR("LAYOUTITEM2","PRIM_TBLO","Item");
var C8=this.cR("TREE","PRIM_TREE");var C9=this.cR("LABEL1","PRIM_LABL");this.cD("ACTIVEDESIGN");C0.iC();C1.setDesignManager(C0);C1.setWidth(800);C1.iC();C2.iC();C3.setDisplayPosition(2);C3.setParent(C2);C3.setHeight(c1);C3.iC();C4.setDisplayPosition(1);C4.setParent(C2);C4.iC();C5.setDisplayPosition(1);C5.setParent(C2);C5.setHeight(60);C5.setUnits("PIXELS");C5.iC();C6.setColumn(C4);C6.setManage(C8);C6.setParent(C2);C6.setRow(C3);C6.setSizing("CONTENTHEIGHTFITTOWIDTH");C6.setAlignment("TOPCENTER");
C6.iC();C7.setColumn(C4);C7.setManage(C9);C7.setParent(C2);C7.setRow(C5);C7.iC();C8.setDisplayPosition(1);C8.setLeft(0);C8.setParent(this);C8.setTabPosition(1);C8.setTop(60);C8.setHeight(375);C8.setWidth(720);C8.iC();C9.setCaption("Title");C9.setDisplayPosition(2);C9.setEllipses("WORD");C9.setHeight(60);C9.setLeft(0);C9.setParent(this);C9.setTabPosition(2);C9.setTabStop(false);C9.setTop(0);C9.setVerticalAlignment("CENTER");C9.setWidth(720);C9.setThemeDrawStyle("Title+DarkTitle");C9.setMarginLeft(4);
C9.iC();C8.aDS("XDEMO_70");C8.aLF({"XEMPLOYID":f.F1,"XEMPTITLE":f.F2,"XSURNAME":f.F3,"XGIVENAME":f.F4,"XEMPDOB":f.F5,"XGENDER":f.F6,"XSTREET":f.F7,"XCITY":f.F8,"XSTATE":f.F9,"XPOSTCODE":f.F10,"XCOUNTRY":f.F11,"XPHONEHME":f.F12,"XPHONEBUS":f.F13,"XPHONEMOB":f.F14,"XSALARY":f.F15,"XSTARTDTE":f.F16,"XTERMDATE":f.F17,"XDEPTMENT":f.F18,"XEMPTHM":f.F19,"XEMPIMG":f.F20});this.setHeight(728);this.setWidth(720);this.setLayoutManager(C2);this.setTheme(l.THEME().get("2015BLUE"));this.setDesignManager(C0);this.aH("CREATEINSTANCE",this,e1);
this.aH("DESIGNCHANGED",this,e2);}});function e1(sender,Ps){var r=l.eR(this,cO,"#Com_owner.CreateInstance",20);r.ln=20;{r.ln=22;this.mthLOAD();}r.ln=24;r.e();};function e2(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Com_owner.DesignChanged",26);var P0=Ps.r("DESIGN");r.ln=26;{r.ln=28;this.srACTIVEDESIGN(P0);}r.ln=30;r.e();};cO.mthLOAD=function(){var m=this.REF,r=l.mR(this,cO,"Load",32);var C0=r.cDR("GETEMPLOYEES","XDEMOW_84","GETEMPLOYEES");C0.iC();r.ln=32;{r.ln=36;C0.mthEXECUTEASYNC({},{LIST:{"EMPLOYEES":m.TREE}});
}r.ln=38;r.e();};cO.getACTIVEDESIGN=function(){return this.REF.ACTIVEDESIGN;};{Fd.F2.Dc=function(){this.aN.call(this,Fd.F2);};l.cFC({co:Fd.F2.Dc,an:"PRIM_FLD",fn:"XEMPTITLE"});Fd.F2.pl=function(){this.aN.call(this);var C0=this.cR("PKIT_1","PRIM_PKIT");var C1=this.cR("PKIT_2","PRIM_PKIT");var C2=this.cR("PKIT_3","PRIM_PKIT");var C3=this.cR("PKIT_4","PRIM_PKIT");var C4=this.cR("PKIT_5","PRIM_PKIT");C0.setValue("Mr");C0.setCaption("Mr");C0.setParent(this);C0.iC();C1.setValue("Mrs");C1.setCaption("Mrs");
C1.setParent(this);C1.iC();C2.setValue("Miss");C2.setCaption("Miss");C2.setParent(this);C2.iC();C3.setValue("Ms");C3.setCaption("Ms");C3.setParent(this);C3.iC();C4.setValue("Dr");C4.setCaption("Dr");C4.setParent(this);C4.iC();this.setNoMatchAction("SHOWVALUE");};l.cFC({co:Fd.F2.pl,an:"PRIM_PKLT",fn:"XEMPTITLE",cn:"Picklist"});}{Fd.F6.Dc=function(){this.aN.call(this,Fd.F6);};l.cFC({co:Fd.F6.Dc,an:"PRIM_FLD",fn:"XGENDER"});Fd.F6.pl=function(){this.aN.call(this);var C0=this.cR("ITEM_1","PRIM_PKIT");
var C1=this.cR("ITEM_2","PRIM_PKIT");var C2=this.cR("ITEM_3","PRIM_PKIT");C0.setCaption("Male");C0.setParent(this);C0.setValue("Male");C0.iC();C1.setCaption("Female");C1.setParent(this);C1.setValue("Female");C1.iC();C2.setCaption("Not Disclosed");C2.setParent(this);C2.setValue("NoDisclose");C2.iC();this.setNoMatchAction("SHOWVALUE");};l.cFC({co:Fd.F6.pl,an:"PRIM_PKLT",fn:"XGENDER",cn:"Picklist"});}cO.srACTIVEDESIGN=function(rn){this.sR("ACTIVEDESIGN",rn);};},{rp:["PRIM_WEB","PRIM_DESN","PRIM_DESN.Design","PRIM_TBLO","PRIM_TBLO.Row","PRIM_TBLO.Column","PRIM_TBLO.Item","PRIM_TREE","PRIM_LABL","PRIM_WEB.DataRequest","PRIM_PKLT"],
dc:["XDEMO_70"],dp:["PRIM_DESN.Design"]});