LANSA.addComponent({id:"XDOBAR",nm:"xDOActionBar",ot:"rp",tp:"Reusable Part",de:"Default Actionbar",tl:14010001},function(l,oI,u){var rc1=l.cB("xdoimg14.png");var rc2=l.cB("xdoimg08.png");var rc3=l.cB("xdoimg01.png");var rc4=l.cB("xdoimg02.png");var rc5=l.cB("xdoimg15.png");var rc6=l.cB("xdoimg11.png");var cO=l.rC(oI,{an:"XDOPANL",mt:{HandleMainPanel:{},HandleDetailPanel:{ps:{"Title":{pt:"i"}}},SetDisplayIcons:{},HideAllIcons:{},DisplayIconWithSpin:{ps:{"Icon":{pt:"i"},"Angle":{pt:"i"},"Duration":
{pt:"i"},"Delay":{pt:"i"}}},SetOpacity:{ps:{"Opacity":{pt:"i"}}},InitSpinner:{}},co:function(){cO.aN.call(this);var C0=this.cR("STYLE1","PRIM_VS","Style");var C1=this.cR("BRUSH1","PRIM_VS","SolidBrush");var C2=this.cR("TABLELAYOUT","PRIM_TBLO");var C3=this.cR("COLUMN1","PRIM_TBLO","Column");var C4=this.cR("COLUMN2","PRIM_TBLO","Column");var C5=this.cR("COLUMN3","PRIM_TBLO","Column");var C6=this.cR("COLUMN4","PRIM_TBLO","Column");var C7=this.cR("ROW1","PRIM_TBLO","Row");var C8=this.cR("LAYOUTITEM2","PRIM_TBLO","Item");
var C9=this.cR("MENUICONITEM1","PRIM_TBLO","Item");var C10=this.cR("BACKICONITEM1","PRIM_TBLO","Item");var C11=this.cR("LAYOUTITEM3","PRIM_TBLO","Item");var C12=this.cR("LAYOUTITEM4","PRIM_TBLO","Item");var C13=this.cR("LAYOUTITEM5","PRIM_TBLO","Item");var C14=this.cR("LAYOUTITEM6","PRIM_TBLO","Item");var C15=this.cR("TITLETEXT","PRIM_LABL");var C16=this.cR("MENUICON","PRIM_IMAG");var C17=this.cR("BACKICON","PRIM_IMAG");var C18=this.cR("SAVEICON","PRIM_IMAG");var C19=this.cR("DELETEICON","PRIM_IMAG");
var C20=this.cR("REFRESHICON","PRIM_IMAG");var C21=this.cR("APPICON","PRIM_IMAG");this.cD("ACTIVEEMPLOYEE");this.cD("SHOWSPIN");this.cD("SHOWSPINROTATION");C0.setBackgroundBrush(C1);C0.iC();C1.setColor("56:142:60");C1.iC();C2.iC();C3.setDisplayPosition(1);C3.setParent(C2);C3.setWidth(75);C3.setUnits("PIXELS");C3.iC();C4.setDisplayPosition(2);C4.setParent(C2);C4.setWidth(2);C4.iC();C5.setDisplayPosition(3);C5.setParent(C2);C5.setWidth(55);C5.setUnits("PIXELS");C5.iC();C6.setDisplayPosition(4);C6.setParent(C2);
C6.setWidth(75);C6.setUnits("PIXELS");C6.iC();C7.setDisplayPosition(1);C7.setParent(C2);C7.iC();C8.setAlignment("CENTERLEFT");C8.setColumn(C4);C8.setFlow("DOWN");C8.setManage(C15);C8.setParent(C2);C8.setRow(C7);C8.setMarginLeft(5);C8.setMarginRight(5);C8.iC();C9.setManage(C16);C9.setParent(C2);C9.setRow(C7);C9.setColumn(C3);C9.setMarginLeft(10);C9.setMarginRight(10);C9.setMarginTop(10);C9.setMarginBottom(10);C9.iC();C10.setManage(C17);C10.setParent(C2);C10.setRow(C7);C10.setColumn(C3);C10.setMarginLeft(10);
C10.setMarginRight(10);C10.setMarginTop(10);C10.setMarginBottom(10);C10.iC();C11.setColumn(C6);C11.setManage(C18);C11.setParent(C2);C11.setRow(C7);C11.setFlow("DOWN");C11.setMarginTop(15);C11.setMarginBottom(15);C11.setMarginLeft(15);C11.setMarginRight(15);C11.iC();C12.setColumn(C5);C12.setManage(C19);C12.setParent(C2);C12.setRow(C7);C12.setFlow("DOWN");C12.setMarginTop(15);C12.setMarginBottom(15);C12.setMarginLeft(10);C12.iC();C13.setColumn(C6);C13.setManage(C20);C13.setParent(C2);C13.setRow(C7);
C13.setMarginTop(15);C13.setMarginLeft(15);C13.setMarginBottom(15);C13.setMarginRight(15);C13.iC();C14.setColumn(C3);C14.setManage(C21);C14.setParent(C2);C14.setRow(C7);C14.setMarginTop(10);C14.setMarginBottom(10);C14.setMarginLeft(10);C14.setMarginRight(10);C14.iC();C15.setCaption("Login");C15.setDisplayPosition(1);C15.setEllipses("WORD");C15.setHeight(55);C15.setLeft(80);C15.setParent(this);C15.setTabPosition(1);C15.setTabStop(false);C15.setTop(0);C15.setVerticalAlignment("CENTER");C15.setWidth(285);
C15.setThemeDrawStyle("Heading1");C15.iC();C16.setDisplayPosition(2);C16.setHeight(35);C16.setParent(this);C16.setTabPosition(2);C16.setTabStop(false);C16.setWidth(55);C16.setImage(rc1);C16.setVisible(false);C16.iC();C17.setDisplayPosition(3);C17.setHeight(35);C17.setParent(this);C17.setTabPosition(3);C17.setTabStop(false);C17.setWidth(55);C17.setVisible(false);C17.setImage(rc2);C17.iC();C18.setDisplayPosition(4);C18.setHeight(25);C18.setImage(rc3);C18.setLeft(440);C18.setParent(this);C18.setTabPosition(4);
C18.setTabStop(false);C18.setTop(15);C18.setWidth(45);C18.setVisible(false);C18.iC();C19.setDisplayPosition(5);C19.setHeight(25);C19.setImage(rc4);C19.setLeft(380);C19.setParent(this);C19.setTabPosition(5);C19.setTabStop(false);C19.setTop(15);C19.setWidth(45);C19.setVisible(false);C19.iC();C20.setDisplayPosition(6);C20.setHeight(25);C20.setImage(rc5);C20.setLeft(440);C20.setParent(this);C20.setTabPosition(6);C20.setTabStop(false);C20.setTop(15);C20.setWidth(45);C20.setVisible(false);C20.iC();C21.setDisplayPosition(7);
C21.setHeight(35);C21.setImage(rc6);C21.setParent(this);C21.setTabPosition(7);C21.setTabStop(false);C21.setWidth(55);C21.iC();C16.aH("CLICK",this,e10);C17.aH("CLICK",this,e6);C18.aH("CLICK",this,e7);C19.aH("CLICK",this,e8);C20.aH("CLICK",this,e9);this.REF.GAPPLICATION.ref.aH("MAINOPENED",this,e1);this.REF.GAPPLICATION.ref.aH("CLOSESEARCH",this,e1);this.REF.GAPPLICATION.ref.aH("DETAILOPENED",this,e2);this.REF.GAPPLICATION.ref.aH("ONPANELSCROLLED",this,e3);this.REF.GAPPLICATION.ref.aH("ONSYNCCOMPLETED",this,e5);
this.setLayoutManager(C2);this.setHeight(55);this.setWidth(500);this.setStyle(C0);}});function e1(sender,Ps){var r=l.eR(this,cO,"#gApplication.MainOpened #gApplication.CloseSearch",44);r.ln=44;{r.ln=46;this.mthHANDLEMAINPANEL();}r.ln=48;r.e();};function e2(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#gApplication.DetailOpened",51);var P0=Ps.r("EMPLOYEEDOCUMENT");r.ln=51;{r.ln=53;this.srACTIVEEMPLOYEE(P0);r.ln=55;cO.mthHANDLEDETAILPANEL.call(this,l.cat(l.cat(m.ACTIVEEMPLOYEE.getGIVENNAME()," "),m.ACTIVEEMPLOYEE.getSURNAME()));
}r.ln=57;r.e();};function e3(sender,Ps){var r=l.eR(this,cO,"#gApplication.onPanelScrolled",60);var P0=Ps.r("POSITION");r.ln=60;{r.ln=62;cO.mthSETOPACITY.call(this,P0.get());}r.ln=64;r.e();};function e4(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#ActiveEmployee.changed",67);var P0=Ps.r("PROPERTY");r.ln=67;{r.ln=69;if(l.tB(l.or(l.s.eq(P0.get(),"SURNAME"),l.s.eq(P0.get(),"GIVENAME")))){r.ln=71;m.TITLETEXT.setCaption(l.cat(l.cat(m.ACTIVEEMPLOYEE.getGIVENNAME()," "),m.ACTIVEEMPLOYEE.getSURNAME()));}}r.ln=75;
r.e();};function e5(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#gApplication.onSyncCompleted",78);var P0=Ps.r("SUCCESS");r.ln=78;{r.ln=81;if(l.not(this.REF.GAPPLICATION.ref.getISEDITING())){r.ln=83;this.mthINITSPINNER();r.ln=84;m.REFRESHICON.setVisible(l.not(this.REF.GDATA.ref.getSYNCEDWITHSERVER()));}}r.ln=88;r.e();};function e6(sender,Ps){var r=l.eR(this,cO,"#BackIcon.Click",91);r.ln=91;{r.ln=93;l.WEB().getHistory().mthGOBACK(u);}r.ln=95;r.e();};function e7(sender,Ps){var r=l.eR(this,cO,"#SaveIcon.Click",97);
r.ln=97;{r.ln=99;this.REF.GAPPLICATION.ref.mthSAVEREQUESTED();}r.ln=101;r.e();};function e8(sender,Ps){var r=l.eR(this,cO,"#DeleteIcon.Click",103);r.ln=103;{r.ln=105;l.WEB().getHistory().mthGOBACK(u);r.ln=107;this.REF.GAPPLICATION.ref.mthDELETEREQUESTED();}r.ln=109;r.e();};function e9(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#RefreshIcon.Click",111);r.ln=111;{r.ln=113;cO.mthDISPLAYICONWITHSPIN.call(this,m.REFRESHICON,360,750,1);r.ln=115;this.REF.GAPPLICATION.ref.mthSYNCALLCHANGES();}r.ln=117;r.e();
};function e10(sender,Ps){var r=l.eR(this,cO,"#MenuIcon.Click",119);r.ln=119;{r.ln=121;this.REF.GAPPLICATION.ref.mthOPENMENU();}r.ln=123;r.e();};function e11(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#ShowSpin.Ended",126);r.ln=126;{r.ln=129;if((m.SHOWSPINROTATION.getManage()===m.REFRESHICON)){r.ln=131;m.SHOWSPIN.mthSTART();}}r.ln=135;r.e();};cO.mthHANDLEMAINPANEL=function(){var m=this.REF,r=l.mR(this,cO,"HandleMainPanel",141);r.ln=141;{r.ln=143;cO.mthSETOPACITY.call(this,-100);r.ln=144;m.TITLETEXT.setCaption("Employees");
r.ln=145;this.mthSETDISPLAYICONS();}r.ln=147;r.e();};cO.mthHANDLEDETAILPANEL=function(p0){var m=this.REF,r=l.mR(this,cO,"HandleDetailPanel",149);var P0=r.cP("TITLE","PRIM_ALPH");P0.set(p0);r.ln=149;{r.ln=152;cO.mthSETOPACITY.call(this,0);r.ln=154;if(l.tB(l.s.ne(P0.get()," "))){r.ln=156;m.TITLETEXT.setCaption(P0.get());}else{r.ln=160;m.TITLETEXT.setCaption("New");}r.ln=164;this.mthSETDISPLAYICONS();}r.ln=166;r.e();};cO.mthSETDISPLAYICONS=function(){var m=this.REF,r=l.mR(this,cO,"SetDisplayIcons",168);
r.ln=168;{r.ln=170;this.mthHIDEALLICONS();r.ln=172;if(this.REF.GAPPLICATION.ref.getISEDITING()){r.ln=174;cO.mthDISPLAYICONWITHSPIN.call(this,m.BACKICON);r.ln=175;m.DELETEICON.setVisible(l.s.ne(m.TITLETEXT.getCaption(),"New"));r.ln=176;m.SAVEICON.setVisible(true);}else{r.ln=180;cO.mthDISPLAYICONWITHSPIN.call(this,m.MENUICON);r.ln=181;m.REFRESHICON.setVisible(l.not(this.REF.GDATA.ref.getSYNCEDWITHSERVER()));}}r.ln=185;r.e();};cO.mthHIDEALLICONS=function(){var m=this.REF,r=l.mR(this,cO,"HideAllIcons",188);
r.ln=188;{r.ln=190;m.APPICON.setVisible(false);r.ln=191;m.MENUICON.setVisible(false);r.ln=192;m.BACKICON.setVisible(false);r.ln=193;m.SAVEICON.setVisible(false);r.ln=194;m.DELETEICON.setVisible(false);r.ln=195;m.REFRESHICON.setVisible(false);}r.ln=197;r.e();};cO.mthDISPLAYICONWITHSPIN=function(p0,p1,p2,p3){var m=this.REF,r=l.mR(this,cO,"DisplayIconWithSpin",199);var P0=r.cPD("ICON");var P1=r.cP("ANGLE","PRIM_NMBR");var P2=r.cP("DURATION","PRIM_NMBR");var P3=r.cP("DELAY","PRIM_NMBR");P0=p0;P1.set((p1===u)?(180):(p1));
P2.set((p2===u)?(200):(p2));P3.set((p3===u)?(400):(p3));r.ln=199;{r.ln=206;this.mthINITSPINNER();r.ln=209;P0.setRotation(0);r.ln=210;m.SHOWSPINROTATION.setAngle(0);r.ln=213;P0.setVisible(true);r.ln=216;m.SHOWSPINROTATION.setManage(P0);r.ln=217;m.SHOWSPINROTATION.setAngle(P1.get());r.ln=218;m.SHOWSPINROTATION.setStartTime(P3.get());r.ln=219;m.SHOWSPINROTATION.setDuration(P2.get());r.ln=222;m.SHOWSPIN.mthSTART();}r.ln=224;r.e();};cO.mthSETOPACITY=function(p0){var m=this.REF,r=l.mR(this,cO,"SetOpacity",227);
var P0=r.cP("OPACITY","PRIM_NMBR");P0.set(p0);r.ln=227;{r.ln=230;m.BRUSH1.setOpacity(l.mul(P0.get(),-1));}r.ln=232;r.e();};cO.mthINITSPINNER=function(){var m=this.REF,r=l.mR(this,cO,"InitSpinner",235);r.ln=235;{r.ln=238;this.srSHOWSPIN(l.cC("PRIM_ANIM"));r.ln=239;this.srSHOWSPINROTATION(l.cC("PRIM_ANIM","Rotate"));r.ln=240;m.SHOWSPINROTATION.setParent(m.SHOWSPIN);}r.ln=242;r.e();};cO.srACTIVEEMPLOYEE=function(rn){if(this.REF.ACTIVEEMPLOYEE!=null){this.REF.ACTIVEEMPLOYEE.rH("CHANGED",this,e4);}this.sR("ACTIVEEMPLOYEE",rn);
if(this.REF.ACTIVEEMPLOYEE!=null){this.REF.ACTIVEEMPLOYEE.aH("CHANGED",this,e4);}};cO.srSHOWSPIN=function(rn){if(this.REF.SHOWSPIN!=null){this.REF.SHOWSPIN.rH("ENDED",this,e11);}this.sR("SHOWSPIN",rn);if(this.REF.SHOWSPIN!=null){this.REF.SHOWSPIN.aH("ENDED",this,e11);}};cO.srSHOWSPINROTATION=function(rn){this.sR("SHOWSPINROTATION",rn);};},{rc:["XDOPANL"],rp:["PRIM_VS.Style","PRIM_VS.SolidBrush","PRIM_TBLO","PRIM_TBLO.Column","PRIM_TBLO.Row","PRIM_TBLO.Item","PRIM_LABL","PRIM_IMAG"],dc:["XDOEMPDOC"],
dp:["PRIM_ANIM","PRIM_ANIM.Rotate"]});