LANSA.addComponent({id:"XDTOOL_6",nm:"xDToolsDataProduct",ot:"rp",tp:"Reusable Part",de:"Product",tl:14020000},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")||(l.gCL()=="LLL")){cL=l.gCL();}var Fd={F1:{nm:"XSPRDID",an:"XSProductID",ft:"A",ln:10,dc:0,lb:{"ENG":"Product ID","FRA":"Product Categor","JPN":"Product ID","LLL":"Product ID"}[cL],h1:"Product",h2:{"ENG":"ID","FRA":"Category","JPN":"ID","LLL":"ID"}[cL],h3:{"ENG":" ","FRA":"ID","JPN":" ","LLL":""}[cL],de:"Product ID",dv:"",
ia:["FE"]},F2:{nm:"XSPRDCTID",an:"XSProductCategoryID",ft:"A",ln:10,dc:0,lb:{"ENG":"Product Categry","FRA":"Product Categor","JPN":"Product Categry","LLL":"Product Categry"}[cL],h1:"Product",h2:"Category",h3:"ID",de:"Product Category ID",dv:"",ia:["FE"]},F3:{nm:"XSPRDLNID",an:"XSProductLineID",ft:"A",ln:10,dc:0,lb:"Product Categor",h1:"Product",h2:"Category",h3:"ID",de:{"ENG":"Product Line ID","FRA":"Product Category ID","JPN":"Product Line ID","LLL":"Product Line ID"}[cL],dv:"",ia:["FE"]},F4:{nm:"XSPRDDSC",
an:"XSProductDescription",ft:"C",ln:100,dc:0,lb:{"ENG":"Product Desc","FRA":"Last Name","JPN":"Product Desc","LLL":"Product Desc"}[cL],h1:{"ENG":"Product","FRA":"Last","JPN":"Product","LLL":"Product"}[cL],h2:{"ENG":"Description","FRA":"Name","JPN":"Description","LLL":"Description"}[cL],h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"Product Description",dv:"",ia:["FE","LC"]},F5:{nm:"XSPRDMDL",an:"XSProductModel",ft:"C",ln:100,dc:0,lb:{"ENG":"Product Model","FRA":"Product Detail","JPN":"Product Model","LLL":"Product Model"}[cL],
h1:"Product",h2:{"ENG":"Model","FRA":"Detail","JPN":"Model","LLL":"Model"}[cL],h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:{"ENG":"Product Model","FRA":"Product Detail","JPN":"Product Model","LLL":"Product Model"}[cL],dv:"",ia:["FE"]},F6:{nm:"XSPRDPRC",an:"XSProductPrice",ft:"S",ln:9,dc:2,ec:"3",lb:"Product Price",h1:"Product",h2:"Price",h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"Product Price",dv:0,ia:["FE","RB"]},F7:{nm:"XSPRDDTL",an:"XSProductDetail",ft:"C",ln:100,dc:0,lb:"Product Detail",
h1:"Product",h2:"Detail",h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"Product Detail",dv:"",ia:["FE"]},F8:{nm:"XSPRDSHP",an:"XSProductShipping",ft:"S",ln:9,dc:2,ec:"3",lb:"Product Price",h1:"Product",h2:"Price",h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:{"ENG":"Product Shipping Cost","FRA":"Product Price","JPN":"Product Shipping Cost","LLL":"Product Shipping Cost"}[cL],dv:0,ia:["FE","RB"]},F9:{nm:"XSPRDSTS",an:"XSProductStockStatus",ft:"A",ln:10,dc:0,lb:"Product Stock S",h1:"Product",
h2:"Stock",h3:"Status",de:"Product Stock Status",dv:"",ia:["FE"]},F10:{nm:"XSPRDTAX",an:"XSProductTaxPercent",ft:"S",ln:5,dc:2,lb:{"ENG":"Product Tax %","FRA":"Discount Percen","JPN":"Product Tax %","LLL":"Product Tax %"}[cL],h1:{"ENG":"Product","FRA":"Discount","JPN":"Product","LLL":"Product"}[cL],h2:{"ENG":"Tax %","FRA":"Percentage","JPN":"Tax %","LLL":"Tax %"}[cL],h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:{"ENG":"Product Tax %","FRA":"Discount Percentage","JPN":"Product Tax %","LLL":"Product Tax %"}[cL],
dv:0,ia:["FE","RB"]},F11:{nm:"XSPRODIMG",an:"XSProductImage",ft:"BL",ln:0,dc:0,lb:"Product Image",h1:"Product",h2:"Image",h3:{"ENG":" ","FRA":" ","JPN":" ","LLL":""}[cL],de:"Product Image",dv:l.SqlNull,ia:["ASQN","FE","LC"]}};var cO=l.rC(oI,{an:"XDTOOL_5",fd:Fd,pt:{ID:{da:"r"},Description:{da:"r"},Model:{da:"r"},Price:{da:"r"},Detail:{da:"r"},ShippingCost:{da:"r"},StockStatus:{da:"na"},TaxPercentage:{da:"r"},Image:{da:"na"},ImagePath:{da:"r"},ProductCategory:{da:"na"},ProductLine:{da:"na"}},co:function()
{cO.aN.call(this);var f=this.aF("XDTOOL_6",Fd);this.cD("GIMAGE");this.aLF({"XSPRDID":f.F1,"XSPRDCTID":f.F2,"XSPRDLNID":f.F3,"XSPRDDSC":f.F4,"XSPRDMDL":f.F5,"XSPRDPRC":f.F6,"XSPRDDTL":f.F7,"XSPRDSHP":f.F8,"XSPRDSTS":f.F9,"XSPRDTAX":f.F10,"XSPRODIMG":f.F11});}});cO.mthGETPRODUCTCATEGORY=function(){var f=this.FLD.XDTOOL_6,r=l.pR(this,cO,"GetProductCategory",20);var P0=r.cPD("PROPERTY");r.ln=20;{r.ln=23;P0=r.sR("P0",this.REF.GDATAMODEL.ref.mthFINDPRODUCTCATEGORY(f.F2.get()));}r.ln=25;return r.rR(P0);
};cO.mthGETPRODUCTLINE=function(){var f=this.FLD.XDTOOL_6,r=l.pR(this,cO,"GetProductLine",27);var P0=r.cPD("PROPERTY");r.ln=27;{r.ln=30;P0=r.sR("P0",this.REF.GDATAMODEL.ref.mthFINDPRODUCTLINE(f.F3.get()));}r.ln=32;return r.rR(P0);};cO.mthGETIMAGE=function(){var f=this.FLD.XDTOOL_6,m=this.REF,r=l.pR(this,cO,"GetImage",34);var P0=r.cPD("PROPERTY");r.ln=34;{r.ln=37;if((m.GIMAGE==null)){r.ln=39;l.APPL().mthCREATEBITMAP(f.F11.get());}r.ln=43;P0=r.sR("P0",m.GIMAGE);}r.ln=45;return r.rR(P0);};cO.mthGETSTOCKSTATUS=function()
{var f=this.FLD.XDTOOL_6,r=l.pR(this,cO,"GetStockStatus",47);var P0=r.cP("PROPERTY","PRIM_ALPH");r.ln=47;{r.ln=50;{var v1=f.F9.get();if(r.ln=51,l.s.eq(v1,"INSTOCK")){r.ln=53;P0.set("In Stock");}else if(r.ln=55,l.s.eq(v1,"BACKORDER")){r.ln=57;P0.set("Back Order");}else{r.ln=61;P0.set(f.F9.get());}r.ln=63;}}r.ln=65;return r.rV(P0.get());};cO.getID=function(){var f=this.FLD.XDTOOL_6;return f.F1.get();};cO.getDESCRIPTION=function(){var f=this.FLD.XDTOOL_6;return f.F4.get();};cO.getMODEL=function(){var f=this.FLD.XDTOOL_6;
return f.F5.get();};cO.getPRICE=function(){var f=this.FLD.XDTOOL_6;return f.F6.get();};cO.getDETAIL=function(){var f=this.FLD.XDTOOL_6;return f.F7.get();};cO.getSHIPPINGCOST=function(){var f=this.FLD.XDTOOL_6;return f.F8.get();};cO.getSTOCKSTATUS=function(){return this.mthGETSTOCKSTATUS();};cO.getTAXPERCENTAGE=function(){var f=this.FLD.XDTOOL_6;return f.F10.get();};cO.getIMAGE=function(){return this.mthGETIMAGE();};cO.getIMAGEPATH=function(){var f=this.FLD.XDTOOL_6;return f.F11.get();};cO.getPRODUCTCATEGORY=function()
{return this.mthGETPRODUCTCATEGORY();};cO.getPRODUCTLINE=function(){return this.mthGETPRODUCTLINE();};cO.srGIMAGE=function(rn){this.sR("GIMAGE",rn);};},{rc:["XDTOOL_5"],dp:["PRIM_BMP"]});