LANSA.addComponent({id:"XSEMAIL",nm:"XSEmail",ot:"rp",tp:"Reusable Part",de:"Email Us",tl:14010001},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")||(l.gCL()=="LLL")){cL=l.gCL();}var Fd={F1:{nm:"XSTMPEML",ft:"C",ln:200,dc:0,lb:{"ENG":"Email","FRA":"Email","JPN":"?","LLL":"Email"}[cL],h1:{"ENG":"Email","FRA":"Email","JPN":"?","LLL":"Email"}[cL],h2:"",h3:"",de:{"ENG":"Temporary Email","FRA":"Email","JPN":"?","LLL":"Temporary Email"}[cL],dv:"",ia:["FE","LC"]},F2:{nm:"XSEMLMSG",ft:"C",
ln:1024,dc:0,lb:{"ENG":"Email Message","FRA":"Email Message","JPN":"?","LLL":"Email Message"}[cL],h1:{"ENG":"Email","FRA":"Email","JPN":"?","LLL":"Email"}[cL],h2:{"ENG":"Message","FRA":"Message","JPN":"","LLL":"Message"}[cL],h3:"",de:{"ENG":"Email Message","FRA":"Email Message","JPN":"?","LLL":"Email Message"}[cL],dv:"",ia:["FE","LC"]},F3:{nm:"WINRETCOD",ft:"P",ln:7,dc:0,lb:"WinRetCod",h1:"WinRetCod",h2:"",h3:"",de:"WinRetCod",dv:0}};var cO=l.rC(oI,{an:"PRIM_PANL",fd:Fd,co:function(){cO.aN.call(this);
this.aF("XSEMAIL",Fd);var C0=this.cR("TABLELAYOUT1","PRIM_TBLO");var C1=this.cR("COLUMN1","PRIM_TBLO","Column");var C2=this.cR("ROW1","PRIM_TBLO","Row");var C3=this.cR("ROW2","PRIM_TBLO","Row");var C4=this.cR("LAYOUTITEM1","PRIM_TBLO","Item");var C5=this.cR("EMAILITEM1","PRIM_TBLO","Item");var C6=this.cR("BODYITEM1","PRIM_TBLO","Item");var C7=this.cR("SENDITEM1","PRIM_TBLO","Item");var C8=this.cR("MESSAGEITEM1","PRIM_TBLO","Item");var C9=this.cR("XSTEMPORARYEMAILITEM1","PRIM_TBLO","Item");var C10=this.cR("TITLE","PRIM_LABL");
var C11=this.cR("BODY","PRIM_TEXT");var C12=this.cF("XSTEMPORARYEMAIL",Fd.F1.VISUAL);var C13=this.cR("SEND","PRIM_PHBN");var C14=this.cR("MESSAGE","PRIM_LABL");var C15=this.cDR("SENDEMAIL","XSSERVER","SENDEMAIL");C0.iC();C1.setDisplayPosition(1);C1.setParent(C0);C1.iC();C2.setDisplayPosition(1);C2.setParent(C0);C2.setHeight(35);C2.setUnits("PIXELS");C2.iC();C3.setDisplayPosition(2);C3.setParent(C0);C3.iC();C4.setAlignment("CENTERLEFT");C4.setColumn(C1);C4.setManage(C10);C4.setParent(C0);C4.setRow(C2);
C4.iC();C5.setColumn(C1);C5.setParent(C0);C5.setRow(C3);C5.setSizing("FITTOWIDTH");C5.setAlignment("TOPLEFT");C5.setFlow("DOWN");C5.setMarginLeft(10);C5.setMarginRight(10);C5.setMarginTop(10);C5.iC();C6.setAlignment("TOPLEFT");C6.setColumn(C1);C6.setManage(C11);C6.setParent(C0);C6.setRow(C3);C6.setSizing("FITTOWIDTH");C6.setFlow("DOWN");C6.setMarginLeft(10);C6.setMarginRight(10);C6.setMarginTop(10);C6.iC();C7.setAlignment("BOTTOMLEFT");C7.setColumn(C1);C7.setManage(C13);C7.setParent(C0);C7.setRow(C3);
C7.setSizing("NONE");C7.setFlow("DOWN");C7.setMarginLeft(10);C7.setMarginTop(10);C7.setMarginBottom(10);C7.iC();C8.setAlignment("BOTTOMRIGHT");C8.setColumn(C1);C8.setManage(C14);C8.setParent(C0);C8.setRow(C3);C8.setSizing("NONE");C8.setFlow("DOWN");C8.setMarginTop(5);C8.setMarginLeft(10);C8.setMarginBottom(10);C8.setMarginRight(10);C8.iC();C9.setAlignment("TOPLEFT");C9.setColumn(C1);C9.setManage(C12);C9.setParent(C0);C9.setRow(C3);C9.setSizing("FITTOWIDTH");C9.setFlow("DOWN");C9.setMarginTop(10);
C9.setMarginLeft(10);C9.setMarginRight(10);C9.iC();C10.setCaption("Need D.I.Y Advice?  Ask us!");C10.setDisplayPosition(1);C10.setEllipses("WORD");C10.setParent(this);C10.setTabPosition(1);C10.setTabStop(false);C10.setVerticalAlignment("CENTER");C10.setWidth(381);C10.setWordWrap(false);C10.setThemeDrawStyle("PanelHeader2");C10.setTop(0);C10.setLeft(0);C10.setMarginLeft(10);C10.setHeight(35);C10.iC();C11.setDisplayPosition(3);C11.setParent(this);C11.setTabPosition(3);C11.setTop(76);C11.setWidth(361);
C11.setHeight(134);C11.iC();C12.setDisplayPosition(2);C12.setParent(this);C12.setTabPosition(2);C12.setLabelType("CAPTION");C12.setLabelPosition("NONE");C12.setMarginLeft(0);C12.setPlaceholder("Enter your email address");C12.setWidth(361);C12.setHeight(21);C12.setUsePicklist(false);C12.setTop(45);C12.setLeft(10);C12.aD();C12.iC();C13.setCaption("Send");C13.setDisplayPosition(4);C13.setParent(this);C13.setTabPosition(4);C13.setTop(213);C13.setWidth(100);C13.setThemeDrawStyle("ButtonLook2");C13.iC();
C14.setDisplayPosition(5);C14.setEllipses("WORD");C14.setHeight(25);C14.setParent(this);C14.setTabPosition(5);C14.setTabStop(false);C14.setTop(213);C14.setVerticalAlignment("CENTER");C14.setWidth(233);C14.setLeft(148);C14.setStyle(l.gTh("XSTHEME01").get("TEXT10RED"));C14.iC();C15.iC();C13.aH("CLICK",this,e1);this.setDisplayPosition(1);this.setHeight(250);this.setLeft(0);this.setTabPosition(1);this.setTop(0);this.setWidth(383);this.setLayoutManager(C0);this.setThemeDrawStyle("Panel1");}});function e1(sender,Ps)
{var f=this.FLD.XSEMAIL,m=this.REF,r=l.eR(this,cO,"#Send.Click",26);r.ln=26;{r.ln=30;m.MESSAGE.setCaption("");r.ln=31;f.F2.set(m.BODY.get());r.ln=33;if(l.s.eq(m.XSTEMPORARYEMAIL.get(),"")){r.ln=35;m.MESSAGE.setCaption("     Try entering an Email address");r.e();return;}r.ln=41;if(l.not(l.s.Contains(m.XSTEMPORARYEMAIL.get(),"@"))){r.ln=43;m.MESSAGE.setCaption("Check your email address");r.e();return;}r.ln=49;if(l.not(l.s.Contains(m.XSTEMPORARYEMAIL.get(),"."))){r.ln=51;m.MESSAGE.setCaption("Check your email address");
r.e();return;}r.ln=57;m.SENDEMAIL.mthEXECUTE({FLD:{"XSACCEML":m.XSTEMPORARYEMAIL.get(),"XSEMLMSG":f.F2.get()}},{FLD:{"WINRETCOD":f.F3}});r.ln=59;if(l.n.eq(f.F3.get(),0)){r.ln=61;m.MESSAGE.setCaption("     Email has been sent");r.e();return;}r.ln=67;m.MESSAGE.setCaption("     Email send failed");}r.ln=69;r.e();};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);};l.cFC({co:Fd.F1.Dc,an:"PRIM_FLD",fn:"XSTMPEML"});Fd.F1.VISUAL=function(){this.aN.call(this,new Fd.F1.Dc());};l.cFC({co:Fd.F1.VISUAL,an:"PRIM_EVEF",fn:"XSTMPEML",cn:"Visual"});
}},{rc:["XSTHEME01"],rp:["PRIM_PANL","PRIM_TBLO","PRIM_TBLO.Column","PRIM_TBLO.Row","PRIM_TBLO.Item","PRIM_LABL","PRIM_TEXT","PRIM_EVEF","PRIM_PHBN","PRIM_WEB.DataRequest"]});