LANSA.addComponent({id:"XSPRDDTA",nm:"XSProductData",ot:"rp",tp:"Reusable Part",de:"Product Object",tl:14010001},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")||(l.gCL()=="LLL")){cL=l.gCL();}var Fd={F1:{nm:"XSPRDID",ft:"A",ln:10,dc:0,lb:{"ENG":"Product ID","FRA":"Product Categor","JPN":"?","LLL":"Product ID"}[cL],h1:{"ENG":"Product","FRA":"Product","JPN":"?","LLL":"Product"}[cL],h2:{"ENG":"ID","FRA":"Category","JPN":"","LLL":"ID"}[cL],h3:{"ENG":"","FRA":"ID","JPN":"","LLL":""}[cL],
de:{"ENG":"Product ID","FRA":"Product ID","JPN":"?","LLL":"Product ID"}[cL],dv:"",ia:["FE"]},F2:{nm:"XSPRDLNID",ft:"A",ln:10,dc:0,lb:{"ENG":"Product Categor","FRA":"Product Categor","JPN":"?","LLL":"Product Categor"}[cL],h1:{"ENG":"Product","FRA":"Product","JPN":"?","LLL":"Product"}[cL],h2:{"ENG":"Category","FRA":"Category","JPN":"","LLL":"Category"}[cL],h3:{"ENG":"ID","FRA":"ID","JPN":"","LLL":"ID"}[cL],de:{"ENG":"Product Line ID","FRA":"Product Category ID","JPN":"?","LLL":"Product Line ID"}[cL],
dv:"",ia:["FE"]},F3:{nm:"XSPRDCTID",ft:"A",ln:10,dc:0,lb:{"ENG":"Product Categry","FRA":"Product Categor","JPN":"?","LLL":"Product Categry"}[cL],h1:{"ENG":"Product","FRA":"Product","JPN":"?","LLL":"Product"}[cL],h2:{"ENG":"Category","FRA":"Category","JPN":"","LLL":"Category"}[cL],h3:{"ENG":"ID","FRA":"ID","JPN":"","LLL":"ID"}[cL],de:{"ENG":"Product Category ID","FRA":"Product Category ID","JPN":"?","LLL":"Product Category ID"}[cL],dv:"",ia:["FE"]},F4:{nm:"XSPRDDSC",ft:"C",ln:100,dc:0,lb:{"ENG":"Product Desc","FRA":"Last Name","JPN":"?","LLL":"Product Desc"}[cL],
h1:{"ENG":"Product","FRA":"Last","JPN":"?","LLL":"Product"}[cL],h2:{"ENG":"Description","FRA":"Name","JPN":"","LLL":"Description"}[cL],h3:"",de:{"ENG":"Product Description","FRA":"Product Description","JPN":"?","LLL":"Product Description"}[cL],dv:"",ia:["FE","LC"]},F5:{nm:"XSPRDMDL",ft:"C",ln:100,dc:0,lb:{"ENG":"Product Model","FRA":"Product Detail","JPN":"?","LLL":"Product Model"}[cL],h1:{"ENG":"Product","FRA":"Product","JPN":"?","LLL":"Product"}[cL],h2:{"ENG":"Model","FRA":"Detail","JPN":"","LLL":"Model"}[cL],
h3:"",de:{"ENG":"Product Model","FRA":"Product Detail","JPN":"?","LLL":"Product Model"}[cL],dv:"",ia:["FE"]},F6:{nm:"XSPRDIMG",ft:"C",ln:200,dc:0,lb:{"ENG":"Image Link","FRA":"Email","JPN":"?","LLL":"Image Link"}[cL],h1:{"ENG":"Image","FRA":"Email","JPN":"?","LLL":"Image"}[cL],h2:{"ENG":"Link","FRA":"","JPN":"","LLL":"Link"}[cL],h3:"",de:{"ENG":"Product Image Link","FRA":"Product Image Link","JPN":"?","LLL":"Product Image Link"}[cL],dv:"",ia:["FE","LC"]},F7:{nm:"XSPRDSTS",ft:"A",ln:10,dc:0,lb:{"ENG":"Product Stock S","FRA":"Product Stock S","JPN":"?","LLL":"Product Stock S"}[cL],
h1:{"ENG":"Product","FRA":"Product","JPN":"?","LLL":"Product"}[cL],h2:{"ENG":"Stock","FRA":"Stock","JPN":"","LLL":"Stock"}[cL],h3:{"ENG":"Status","FRA":"Status","JPN":"","LLL":"Status"}[cL],de:{"ENG":"Product Stock Status","FRA":"Product Stock Status","JPN":"?","LLL":"Product Stock Status"}[cL],dv:"",ia:["FE"]},F8:{nm:"XSPRDPRC",ft:"S",ln:9,dc:2,ec:"3",lb:{"ENG":"Product Price","FRA":"Product Price","JPN":"?","LLL":"Product Price"}[cL],h1:{"ENG":"Product","FRA":"Product","JPN":"?","LLL":"Product"}[cL],
h2:{"ENG":"Price","FRA":"Price","JPN":"","LLL":"Price"}[cL],h3:"",de:{"ENG":"Product Price","FRA":"Product Price","JPN":"?","LLL":"Product Price"}[cL],dv:0,ia:["FE","RB"]},F9:{nm:"XSPRDDTL",ft:"C",ln:100,dc:0,lb:{"ENG":"Product Detail","FRA":"Product Detail","JPN":"?","LLL":"Product Detail"}[cL],h1:{"ENG":"Product","FRA":"Product","JPN":"?","LLL":"Product"}[cL],h2:{"ENG":"Detail","FRA":"Detail","JPN":"","LLL":"Detail"}[cL],h3:"",de:{"ENG":"Product Detail","FRA":"Product Detail","JPN":"?","LLL":"Product Detail"}[cL],
dv:"",ia:["FE"]}};var cO=l.rC(oI,{an:"PRIM_OBJT",fd:Fd,pt:{ID:{da:"r"},Category:{da:"r"},ProductDesc:{da:"r"},ProductModel:{da:"r"},ImageLink:{da:"r"},StockStatus:{da:"r"},UnitPrice:{da:"r"},ProductDetail:{da:"r"}},co:function(){cO.aN.call(this);var f=this.aF("XSPRDDTA",Fd);this.aLF({"XSPRDID":f.F1,"XSPRDLNID":f.F2,"XSPRDCTID":f.F3,"XSPRDDSC":f.F4,"XSPRDMDL":f.F5,"XSPRDIMG":f.F6,"XSPRDSTS":f.F7,"XSPRDPRC":f.F8,"XSPRDDTL":f.F9});var li=this.aL("XSPRDDTA");li.PRODUCTLIST=l.cLT({"XSPRDID":f.F1,"XSPRDLNID":f.F2,"XSPRDCTID":f.F3,"XSPRDDSC":f.F4,"XSPRDMDL":f.F5,"XSPRDIMG":f.F6,"XSPRDSTS":f.F7,"XSPRDPRC":f.F8,"XSPRDDTL":f.F9},null);
}});cO.getID=function(){return this.FLD.XSPRDDTA.F1.get();};cO.getCATEGORY=function(){return this.FLD.XSPRDDTA.F3.get();};cO.getPRODUCTDESC=function(){return this.FLD.XSPRDDTA.F4.get();};cO.getPRODUCTMODEL=function(){return this.FLD.XSPRDDTA.F5.get();};cO.getIMAGELINK=function(){return this.FLD.XSPRDDTA.F6.get();};cO.getSTOCKSTATUS=function(){return this.FLD.XSPRDDTA.F7.get();};cO.getUNITPRICE=function(){return this.FLD.XSPRDDTA.F8.get();};cO.getPRODUCTDETAIL=function(){return this.FLD.XSPRDDTA.F9.get();
};},{rp:["PRIM_OBJT"]});