LANSA.addComponent({id:"XSSHPSM1",nm:"XSShoppingCartSummary",ot:"rp",tp:"Reusable Part",de:"Shopping Cart Summary",tl:14010001},function(l,oI,u){var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")||(l.gCL()=="LLL")){cL=l.gCL();}var Fd={F1:{nm:"XSCRTID",ft:"A",ln:10,dc:0,lb:{"ENG":"Shopping CartID","FRA":"Shopping Cart I","JPN":"?","LLL":"Shopping CartID"}[cL],h1:{"ENG":"Shopping","FRA":"Shopping","JPN":"?","LLL":"Shopping"}[cL],h2:{"ENG":"Cart ID","FRA":"Cart","JPN":"","LLL":"Cart ID"}[cL],h3:{"ENG":"","FRA":"ID","JPN":"","LLL":""}[cL],
de:{"ENG":"Shopping Cart ID","FRA":"Shopping Cart ID","JPN":"?","LLL":"Shopping Cart ID"}[cL],dv:"",ia:["FE"]},F2:{nm:"XSPRDID",ft:"A",ln:10,dc:0,lb:{"ENG":"Product ID","FRA":"Product Categor","JPN":"?","LLL":"Product ID"}[cL],h1:{"ENG":"Product","FRA":"Product","JPN":"?","LLL":"Product"}[cL],h2:{"ENG":"ID","FRA":"Category","JPN":"","LLL":"ID"}[cL],h3:{"ENG":"","FRA":"ID","JPN":"","LLL":""}[cL],de:{"ENG":"Product ID","FRA":"Product ID","JPN":"?","LLL":"Product ID"}[cL],dv:"",ia:["FE"]},F3:{nm:"XSACCEML",
ft:"C",ln:200,dc:0,lb:{"ENG":"Email","FRA":"Email","JPN":"?","LLL":"Email"}[cL],h1:{"ENG":"Email","FRA":"Email","JPN":"?","LLL":"Email"}[cL],h2:"",h3:"",de:{"ENG":"Email","FRA":"Email","JPN":"?","LLL":"Email"}[cL],dv:"",ia:["FE","LC"]},F4:{nm:"XSCRTQTY",ft:"S",ln:7,dc:0,lb:{"ENG":"Quantity","FRA":"Quantity","JPN":"?","LLL":"Quantity"}[cL],h1:{"ENG":"Quantity","FRA":"Quantity","JPN":"?","LLL":"Quantity"}[cL],h2:"",h3:"",de:{"ENG":"Number of items in cart","FRA":"Quantity","JPN":"?","LLL":"Number of items in cart"}[cL],
dv:0,ia:["FE","RB"]},F5:{nm:"XSCRTPRC",ft:"S",ln:9,dc:2,ec:"3",lb:{"ENG":"Cart Ttl Price","FRA":"Product Price","JPN":"?","LLL":"Cart Ttl Price"}[cL],h1:{"ENG":"Cart","FRA":"Product","JPN":"?","LLL":"Cart"}[cL],h2:{"ENG":"Total","FRA":"Price","JPN":"","LLL":"Total"}[cL],h3:{"ENG":"Price","FRA":"","JPN":"","LLL":"Price"}[cL],de:{"ENG":"Cart Total Price","FRA":"Product Price","JPN":"?","LLL":"Cart Total Price"}[cL],dv:0,ia:["FE","RB"]},F6:{nm:"XSSTATUS",ft:"A",ln:2,dc:0,lb:{"ENG":"Status","FRA":"Status","JPN":"?","LLL":"Status"}[cL],
h1:{"ENG":"Status","FRA":"Status","JPN":"?","LLL":"Status"}[cL],h2:"",h3:"",de:{"ENG":"Status","FRA":"Status","JPN":"?","LLL":"Status"}[cL],dv:"",ia:["FE"]}};var cO=l.rC(oI,{an:"PRIM_PPNL",fd:Fd,mt:{AddItemtoCart:{ps:{"ProductID":{pt:"i"}}}},ev:{Continue:{},CartUpdated:{}},co:function(){cO.aN.call(this);this.aF("XSSHPSM1",Fd);var C0=this.cA("MYSESSION","XSMYSSN");var C1=this.cR("TABLELAYOUT1","PRIM_TBLO");var C2=this.cR("COLUMN1","PRIM_TBLO","Column");var C3=this.cR("COLUMN2","PRIM_TBLO","Column");
var C4=this.cR("ROW1","PRIM_TBLO","Row");var C5=this.cR("ROW2","PRIM_TBLO","Row");var C6=this.cR("LITEMADDEDITEM1","PRIM_TBLO","Item");var C7=this.cR("LITEMTOTALITEM1","PRIM_TBLO","Item");var C8=this.cR("LITEMSUMMARYITEM1","PRIM_TBLO","Item");var C9=this.cR("CONTINUEBUTTONITEM1","PRIM_TBLO","Item");var C10=this.cR("SHOPPINGCARTBUTTONITEM1","PRIM_TBLO","Item");var C11=this.cR("LITEMADDED","PRIM_LABL");var C12=this.cR("LITEMSUMMARY","PRIM_LABL");var C13=this.cR("LITEMTOTAL","PRIM_LABL");var C14=this.cR("CONTINUEBUTTON","PRIM_PHBN");
var C15=this.cR("SHOPPINGCARTBUTTON","PRIM_PHBN");var C16=this.cPR("GOTOSHOPPINGCART","XSSERVER","GOTOSHOPPINGCART");var C17=this.cF("CARTID",Fd.F1.Dc);if((C0!=null)&&(C0.iI()==false)){C0.iC();}C1.iC();C2.setDisplayPosition(1);C2.setParent(C1);C2.iC();C3.setDisplayPosition(2);C3.setParent(C1);C3.iC();C4.setDisplayPosition(1);C4.setParent(C1);C4.setHeight(2);C4.iC();C5.setDisplayPosition(2);C5.setParent(C1);C5.iC();C6.setAlignment("TOPLEFT");C6.setColumn(C2);C6.setManage(C11);C6.setParent(C1);C6.setRow(C4);
C6.setSizing("FITTOWIDTH");C6.setFlow("DOWN");C6.setColumnSpan(2);C6.iC();C7.setAlignment("TOPLEFT");C7.setColumn(C2);C7.setManage(C13);C7.setParent(C1);C7.setRow(C4);C7.setSizing("NONE");C7.setFlow("DOWN");C7.setColumnSpan(2);C7.iC();C8.setAlignment("TOPLEFT");C8.setColumn(C2);C8.setManage(C12);C8.setParent(C1);C8.setRow(C4);C8.setSizing("NONE");C8.setFlow("DOWN");C8.setColumnSpan(2);C8.iC();C9.setAlignment("TOPCENTER");C9.setColumn(C2);C9.setManage(C14);C9.setParent(C1);C9.setRow(C5);C9.setSizing("NONE");
C9.iC();C10.setAlignment("TOPCENTER");C10.setColumn(C3);C10.setManage(C15);C10.setParent(C1);C10.setRow(C5);C10.setSizing("NONE");C10.iC();C11.setCaption("Item added to your cart");C11.setDisplayPosition(1);C11.setEllipses("WORD");C11.setHeight(25);C11.setParent(this);C11.setTabPosition(1);C11.setTabStop(false);C11.setTop(0);C11.setVerticalAlignment("CENTER");C11.setWidth(351);C11.setLeft(0);C11.setMarginLeft(20);C11.setThemeDrawStyle("PanelHeader2");C11.iC();C12.setCaption("You have 0 items in your cart");
C12.setDisplayPosition(2);C12.setEllipses("WORD");C12.setHeight(25);C12.setLeft(0);C12.setParent(this);C12.setTabPosition(2);C12.setTabStop(false);C12.setTop(25);C12.setVerticalAlignment("CENTER");C12.setWidth(280);C12.setStyle(l.gTh("XSTHEME01").get("TEXT10BOLDALMOSTBLACK"));C12.setMarginLeft(20);C12.iC();C13.setCaption("Total Cost : $0.00");C13.setDisplayPosition(3);C13.setEllipses("WORD");C13.setHeight(25);C13.setLeft(0);C13.setParent(this);C13.setTabPosition(3);C13.setTabStop(false);C13.setTop(50);
C13.setVerticalAlignment("CENTER");C13.setWidth(280);C13.setStyle(l.gTh("XSTHEME01").get("TEXT10BOLDALMOSTBLACK"));C13.setMarginLeft(20);C13.iC();C14.setCaption("Continue");C14.setDisplayPosition(4);C14.setLeft(13);C14.setParent(this);C14.setTabPosition(4);C14.setTop(90);C14.setWidth(150);C14.setStyle(l.gTh("XSTHEME01").get("BUTTONGN3WH"));C14.setMouseOverStyle(l.gTh("XSTHEME01").get("BUTTONGN2WH"));C14.iC();C15.setCaption("Shopping Cart");C15.setDisplayPosition(5);C15.setParent(this);C15.setTabPosition(5);
C15.setTop(90);C15.setWidth(150);C15.setLeft(188);C15.setStyle(l.gTh("XSTHEME01").get("BUTTONGN3WH"));C15.setMouseOverStyle(l.gTh("XSTHEME01").get("BUTTONGN2WH"));C15.iC();C16.iC();C17.aD();C17.iC();C14.aH("CLICK",this,e1);C15.aH("CLICK",this,e2);this.setHeight(137);this.setLeft(0);this.setTop(0);this.setWidth(353);this.setLayoutManager(C1);this.setStyle(l.gTh("XSTHEME01").get("BACKGROUNDWHITE"));}});function e1(sender,Ps){var r=l.eR(this,cO,"#ContinueButton.Click",41);r.ln=41;{r.ln=43;this.fE("CONTINUE");
r.ln=45;this.mthCLOSEPOPUP();}r.ln=47;r.e();};function e2(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#ShoppingCartButton.Click",49);r.ln=49;{r.ln=51;m.GOTOSHOPPINGCART.mthEXECUTE({},{});}r.ln=53;r.e();};cO.mthADDITEMTOCART=function(p0){var f=this.FLD.XSSHPSM1,m=this.REF,r=l.mR(this,cO,"AddItemtoCart",55);var P0=r.cPF("PRODUCTID",Fd.F2.Dc);P0.set(p0);var C0=r.cDR("ADDTOCART","XSSERVER","ADDTOCART");C0.iC();C0.aH("COMPLETED",this,e3);r.ln=55;{r.ln=60;f.F3.set(m.MYSESSION.ref.mthRESTORELOCALVALUE("EMAIL"));
r.ln=62;m.CARTID.set(m.MYSESSION.ref.mthRESTORELOCALVALUE("CARTID"));f.F1.set(m.MYSESSION.ref.mthRESTORELOCALVALUE("CARTID"));r.ln=65;C0.mthEXECUTEASYNC({FLD:{"XSCRTID":f.F1.get(),"XSACCEML":f.F3.get(),"XSPRDID":P0.get()}},{FLD:{"XSCRTID":f.F1,"XSCRTQTY":f.F4,"XSCRTPRC":f.F5,"XSSTATUS":f.F6}});}r.ln=84;r.e();function e3(sender,Ps){var r=l.eR(this,cO,"#AddtoCart.completed",67);r.ln=67;{r.ln=69;m.LITEMSUMMARY.set(l.cat(l.cat("You have ",l.n.AsString(f.F4.get()))," items in your cart"));r.ln=70;m.LITEMTOTAL.set(l.cat("Total Cost : $",l.n.AsString(f.F5.get())));
r.ln=73;if(l.s.eq(m.CARTID.get(),"")){r.ln=75;m.MYSESSION.ref.mthSAVELOCALVALUE("CARTID",f.F1.get());}r.ln=79;m.MYSESSION.ref.setPCARTQUANTITY(f.F4.get());r.ln=80;m.MYSESSION.ref.setPCARTPRICE(f.F5.get());}r.ln=82;r.e();}};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);};l.cFC({co:Fd.F1.Dc,an:"PRIM_FLD",fn:"XSCRTID"});}{Fd.F2.Dc=function(){this.aN.call(this,Fd.F2);};l.cFC({co:Fd.F2.Dc,an:"PRIM_FLD",fn:"XSPRDID"});}},{rc:["XSMYSSN","XSTHEME01"],rp:["PRIM_PPNL","PRIM_TBLO","PRIM_TBLO.Column","PRIM_TBLO.Row","PRIM_TBLO.Item","PRIM_LABL","PRIM_PHBN","PRIM_WEB.WebPageRequest","PRIM_FLD","PRIM_WEB.DataRequest"]
});