(function(l,u){var oI=l.cV({id:"XDEMOW_36",nm:"xDemoWebMailTo",ot:"wp",tp:"Web Page",de:"Preparing an email",tl:3});var cL="ENG";if((l.gCL()=="FRA")||(l.gCL()=="JPN")||(l.gCL()=="LLL")){cL=l.gCL();}var c1=l.cDec("1.51"),c2=l.cDec("1.74");var rc1=l.cB("xdemow_36-ximageema.png");var Fd={F1:{nm:"XDEMOUN_3",ft:"N",ln:4096,dc:0,lb:"Unicode 4096",h1:"Unicode",h2:"4096",h3:" ",de:"Unicode 4096",dv:"",ia:["FE","LC"]},F2:{nm:"XDEMOAL_1",ft:"A",ln:256,dc:0,lb:{"ENG":"Alpha 256","FRA":"Alpha 128","JPN":"Alpha 128","LLL":"Alpha 256"}[cL],
h1:"Alpha",h2:{"ENG":"256","FRA":"128","JPN":"128","LLL":"256"}[cL],h3:" ",de:{"ENG":"Alpha 256","FRA":"Alpha 128","JPN":"Alpha 128","LLL":"Alpha 256"}[cL],dv:"",ia:["FE","LC"]},F3:{nm:"XDEMOUNIC",ft:"N",ln:128,dc:0,lb:"Unicode 128",h1:"Unicode",h2:"128",h3:" ",de:"Unicode 128",dv:"",ia:["FE","LC"]}};var cO=l.rC(oI,{an:"PRIM_WEB",fd:Fd,mt:{MailTo:{},AddParameter:{ps:{"Name":{pt:"i"},"Value":{pt:"i"}}}},co:function(){cO.aN.call(this);this.aF("XDEMOW_36",Fd);var C0=this.cR("STYLE1","PRIM_VS","Style");
var C1=this.cR("TABLELAYOUT","PRIM_TBLO");var C2=this.cR("COLUMN1","PRIM_TBLO","Column");var C3=this.cR("ROW","PRIM_TBLO","Row");var C4=this.cR("ROW_2","PRIM_TBLO","Row");var C5=this.cR("COLUMN","PRIM_TBLO","Column");var C6=this.cR("COLUMN_2","PRIM_TBLO","Column");var C7=this.cR("LAYOUTITEM1","PRIM_TBLO","Item");var C8=this.cR("LAYOUTITEM2","PRIM_TBLO","Item");var C9=this.cR("LAYOUTITEM3","PRIM_TBLO","Item");var C10=this.cR("LAYOUTITEM4","PRIM_TBLO","Item");var C11=this.cR("LAYOUTITEM5","PRIM_TBLO","Item");
var C12=this.cR("LAYOUTITEM6","PRIM_TBLO","Item");var C13=this.cF("TO",Fd.F1.VISUALEDIT);var C14=this.cF("CC",Fd.F1.VISUALEDIT);var C15=this.cF("BCC",Fd.F1.VISUALEDIT);var C16=this.cF("SUBJECT",Fd.F2.VISUALEDIT);var C17=this.cR("MESSAGE","PRIM_TEXT");var C18=this.cR("SEND","PRIM_PHBN");var C19=this.cR("MAILTO","PRIM_ALPH");var C20=this.cR("PARAMETERS","PRIM_ALPH");C0.setCursor("HAND");C0.iC();C1.iC();C2.setDisplayPosition(1);C2.setParent(C1);C2.setWidth(113);C2.setUnits("PIXELS");C2.iC();C3.setDisplayPosition(1);
C3.setParent(C1);C3.setHeight(118);C3.setUnits("PIXELS");C3.iC();C4.setDisplayPosition(2);C4.setParent(C1);C4.setHeight(c1);C4.iC();C5.setDisplayPosition(2);C5.setParent(C1);C5.setWidth(c2);C5.iC();C6.setDisplayPosition(3);C6.setParent(C1);C6.iC();C7.setAlignment("TOPLEFT");C7.setColumn(C5);C7.setFlow("DOWN");C7.setManage(C13);C7.setParent(C1);C7.setRow(C3);C7.setSizing("FITTOWIDTH");C7.setMarginTop(2);C7.setMarginBottom(2);C7.setColumnSpan(2);C7.setMarginLeft(2);C7.setMarginRight(2);C7.iC();C8.setAlignment("TOPLEFT");
C8.setColumn(C5);C8.setFlow("DOWN");C8.setManage(C14);C8.setParent(C1);C8.setRow(C3);C8.setSizing("FITTOWIDTH");C8.setMarginTop(2);C8.setMarginBottom(2);C8.setColumnSpan(2);C8.setMarginLeft(2);C8.setMarginRight(2);C8.iC();C9.setAlignment("TOPLEFT");C9.setColumn(C5);C9.setFlow("DOWN");C9.setManage(C15);C9.setParent(C1);C9.setRow(C3);C9.setSizing("FITTOWIDTH");C9.setMarginTop(2);C9.setMarginBottom(2);C9.setColumnSpan(2);C9.setMarginLeft(2);C9.setMarginRight(2);C9.iC();C10.setAlignment("TOPLEFT");C10.setColumn(C5);
C10.setFlow("DOWN");C10.setManage(C16);C10.setParent(C1);C10.setRow(C3);C10.setSizing("FITTOWIDTH");C10.setMarginTop(2);C10.setMarginBottom(2);C10.setColumnSpan(2);C10.setMarginLeft(2);C10.setMarginRight(2);C10.iC();C11.setAlignment("TOPLEFT");C11.setColumn(C2);C11.setFlow("DOWN");C11.setManage(C17);C11.setParent(C1);C11.setRow(C4);C11.setColumnSpan(3);C11.setMarginLeft(2);C11.setMarginRight(2);C11.setMarginBottom(2);C11.iC();C12.setAlignment("TOPLEFT");C12.setColumn(C2);C12.setFlow("RIGHT");C12.setManage(C18);
C12.setParent(C1);C12.setRow(C3);C12.setMarginTop(2);C12.setMarginLeft(2);C12.setMarginRight(2);C12.setMarginBottom(2);C12.iC();C13.setDisplayPosition(1);C13.setParent(this);C13.setTabPosition(1);C13.setHeight(25);C13.setWidth(1083);C13.setTop(2);C13.setCaption("To");C13.setLabelType("CAPTION");C13.setMarginLeft(60);C13.setLeft(115);C13.setLabelSelectable(false);C13.aD();C13.iC();C14.setDisplayPosition(2);C14.setParent(this);C14.setTabPosition(2);C14.setTop(31);C14.setHeight(25);C14.setWidth(1083);
C14.setCaption("CC");C14.setLabelType("CAPTION");C14.setMarginLeft(60);C14.setLeft(115);C14.setLabelSelectable(false);C14.aD();C14.iC();C15.setDisplayPosition(3);C15.setParent(this);C15.setTabPosition(3);C15.setTop(60);C15.setHeight(25);C15.setWidth(1083);C15.setCaption("BCC");C15.setLabelType("CAPTION");C15.setMarginLeft(60);C15.setLeft(115);C15.setLabelSelectable(false);C15.aD();C15.iC();C16.setDisplayPosition(4);C16.setParent(this);C16.setTabPosition(4);C16.setTop(89);C16.setHeight(25);C16.setWidth(1083);
C16.setLabelType("CAPTION");C16.setMarginLeft(60);C16.setCaption("Subject");C16.setLeft(115);C16.setLabelSelectable(false);C16.aD();C16.iC();C17.setDisplayPosition(5);C17.setLeft(2);C17.setParent(this);C17.setTabPosition(5);C17.setTop(118);C17.setWidth(1196);C17.setHeight(680);C17.iC();C18.setCaption("Send");C18.setDisplayPosition(6);C18.setLeft(2);C18.setParent(this);C18.setTabPosition(6);C18.setTop(2);C18.setWidth(109);C18.setHeight(114);C18.setImagePosition("ABOVECAPTION");C18.setImage(rc1);C18.setStyle(C0);
C18.iC();C19.iC();C20.iC();C18.aH("CLICK",this,e2);this.setLayoutManager(C1);this.setTheme(l.THEME().get("2015BLUE"));this.aH("INITIALIZE",this,e1);}});function e1(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#Com_owner.Initialize",28);r.ln=28;{r.ln=30;m.TO.set("Sample@_YourSite_.Com");r.ln=31;m.CC.set("CC_Sample@_YourSite_.Com");r.ln=32;m.BCC.set("BCC_Sample@_YourSite_.Com");r.ln=33;m.SUBJECT.set("Sample subject");r.ln=34;m.MESSAGE.set("Sample message content.");}r.ln=36;r.e();};function e2(sender,Ps)
{var r=l.eR(this,cO,"#Send.Click",38);r.ln=38;{r.ln=40;this.mthMAILTO();}r.ln=42;r.e();};cO.mthMAILTO=function(){var m=this.REF,r=l.mR(this,cO,"MailTo",44);r.ln=44;{r.ln=46;m.MAILTO.set(l.s.Substitute("mailto:&1",m.TO.get()));r.ln=48;cO.mthADDPARAMETER.call(this,"CC",m.CC.get());r.ln=49;cO.mthADDPARAMETER.call(this,"BCC",m.BCC.get());r.ln=50;cO.mthADDPARAMETER.call(this,"SUBJECT",m.SUBJECT.get());r.ln=51;cO.mthADDPARAMETER.call(this,"BODY",m.MESSAGE.get());r.ln=53;l.WEB().mthNAVIGATE(l.cat(m.MAILTO.get(),m.PARAMETERS.get()),"CURRENT");
}r.ln=55;r.e();};cO.mthADDPARAMETER=function(p0,p1){var m=this.REF,r=l.mR(this,cO,"AddParameter",57);var P0=r.cPF("NAME",Fd.F3.Dc);var P1=r.cPF("VALUE",Fd.F1.Dc);P0.set(p0);P1.set(p1);r.ln=57;{r.ln=61;if(l.s.eq(m.PARAMETERS.get(),"")){r.ln=63;m.PARAMETERS.set("?");}r.ln=67;if(l.s.ne(m.PARAMETERS.get(),"?")){r.ln=69;m.PARAMETERS.set(l.cat(m.PARAMETERS.get(),"&"));}r.ln=73;if(l.s.eq(P1.get(),"")){r.ln=75;P1.set("???");}r.ln=79;m.PARAMETERS.set(l.cat(m.PARAMETERS.get(),l.s.Substitute("&1=&2",P0.get(),l.s.ReplaceAll(P1.get()," ","%20"))));
}r.ln=81;r.e();};{Fd.F1.Dc=function(){this.aN.call(this,Fd.F1);};l.eC(Fd.F1.Dc,"PRIM_FLD");Fd.F1.VISUALEDIT=function(){this.aN.call(this,new Fd.F1.Dc());this.setComponentVersion(1);this.setHeight(21);this.setUsePicklist(false);this.setWidth(782);};l.eC(Fd.F1.VISUALEDIT,"PRIM_EVEF");}{Fd.F2.Dc=function(){this.aN.call(this,Fd.F2);};l.eC(Fd.F2.Dc,"PRIM_FLD");Fd.F2.VISUALEDIT=function(){this.aN.call(this,new Fd.F2.Dc());this.setComponentVersion(1);this.setHeight(21);this.setUsePicklist(false);this.setWidth(782);
};l.eC(Fd.F2.VISUALEDIT,"PRIM_EVEF");}{Fd.F3.Dc=function(){this.aN.call(this,Fd.F3);};l.eC(Fd.F3.Dc,"PRIM_FLD");}}(window["LANSA"]));