(function(l,u){var oI=l.cV({id:"XSFTRDPRD",nm:"XSFeaturedProducts",ot:"rp",tp:"Reusable Part",de:"Featured Products",tl:3});var cL="ENG";if(l.gCL()=="FRA"){cL=l.gCL();}var Fd={F1:{nm:"XSPRDID",ft:"A",ln:10,dc:0,lb:{"ENG":"Product ID","FRA":"Product Categor"}[cL],h1:"Product",h2:{"ENG":"ID","FRA":"Category"}[cL],h3:{"ENG":" ","FRA":"ID"}[cL],de:"Product ID",dv:"",ia:["FE"]},F2:{nm:"XSPRDLNID",ft:"A",ln:10,dc:0,lb:"Product Categor",h1:"Product",h2:"Category",h3:"ID",de:{"ENG":"Product Line ID","FRA":"Product Category ID"}[cL],
dv:"",ia:["FE"]},F3:{nm:"XSPRDCTID",ft:"A",ln:10,dc:0,lb:{"ENG":"Product Categry","FRA":"Product Categor"}[cL],h1:"Product",h2:"Category",h3:"ID",de:"Product Category ID",dv:"",ia:["FE"]},F4:{nm:"XSPRDDSC",ft:"C",ln:100,dc:0,lb:{"ENG":"Product Desc","FRA":"Last Name"}[cL],h1:{"ENG":"Product","FRA":"Last"}[cL],h2:{"ENG":"Description","FRA":"Name"}[cL],h3:" ",de:"Product Description",dv:"",ia:["FE","LC"]},F5:{nm:"XSPRDMDL",ft:"C",ln:100,dc:0,lb:{"ENG":"Product Model","FRA":"Product Detail"}[cL],h1:"Product",
h2:{"ENG":"Model","FRA":"Detail"}[cL],h3:" ",de:{"ENG":"Product Model","FRA":"Product Detail"}[cL],dv:"",ia:["FE"]},F6:{nm:"XSPRDIMG",ft:"C",ln:200,dc:0,lb:{"ENG":"Image Link","FRA":"Email"}[cL],h1:{"ENG":"Image","FRA":"Email"}[cL],h2:{"ENG":"Link","FRA":" "}[cL],h3:" ",de:"Product Image Link",dv:"",ia:["FE","LC"]},F7:{nm:"XSPRDSTS",ft:"A",ln:10,dc:0,lb:"Product Stock S",h1:"Product",h2:"Stock",h3:"Status",de:"Product Stock Status",dv:"",ia:["FE"]},F8:{nm:"XSPRDPRC",ft:"S",ln:9,dc:2,ec:"3",lb:"Product Price",
h1:"Product",h2:"Price",h3:" ",de:"Product Price",dv:0,ia:["FE","RB"]},F9:{nm:"XSPRDDTL",ft:"C",ln:100,dc:0,lb:"Product Detail",h1:"Product",h2:"Detail",h3:" ",de:"Product Detail",dv:"",ia:["FE"]}};var cO=l.rC(oI,{an:"PRIM_PANL",fd:Fd,co:function(){cO.aN.call(this);var f=this.aF("XSFTRDPRD",Fd);var C0=this.cR("TABLELAYOUT1","PRIM_TBLO");var C1=this.cR("COLUMN1","PRIM_TBLO","Column");var C2=this.cR("ROW1","PRIM_TBLO","Row");var C3=this.cR("ROW3","PRIM_TBLO","Row");var C4=this.cR("LABEL1ITEM1","PRIM_TBLO","Item");
var C5=this.cR("TILEITEM1","PRIM_TBLO","Item");var C6=this.cR("TILEITEM2","PRIM_TBLO","Item");var C7=this.cR("LAYOUTITEM1","PRIM_TBLO","Item");var C8=this.cR("TABLELAYOUT2","PRIM_TBLO");var C9=this.cR("COLUMN2","PRIM_TBLO","Column");var C10=this.cR("ROW2","PRIM_TBLO","Row");var C11=this.cR("NEWPRODUCTSITEM1","PRIM_TBLO","Item");var C12=this.cR("PANEL1","PRIM_PANL");var C13=this.cR("NEWPRODUCTS","PRIM_LABL");var C14=this.cR("TILE","PRIM_TILE");var C15=this.cR("PRODUCTS","PRIM_ACOL");var C16=this.cDR("LOADFEATUREPRODUCTS","XSSERVER","LOADFEATUREPRODUCTS");
C0.iC();C1.setDisplayPosition(1);C1.setParent(C0);C1.iC();C2.setDisplayPosition(1);C2.setParent(C0);C2.setHeight(60);C2.setUnits("PIXELS");C2.iC();C3.setDisplayPosition(2);C3.setParent(C0);C3.iC();C4.setManage(C13);C4.setParent(C0);C4.setRow(C2);C4.setSizing("FITTOWIDTH");C4.setColumn(C1);C4.setAlignment("TOPLEFT");C4.setMarginLeft(3);C4.setMarginTop(3);C4.setMarginRight(3);C4.setMarginBottom(3);C4.setFlow("DOWN");C4.iC();C5.setAlignment("TOPLEFT");C5.setColumn(C1);C5.setParent(C0);C5.setRow(C2);
C5.setSizing("FITTOWIDTH");C5.setFlow("DOWN");C5.iC();C6.setAlignment("TOPLEFT");C6.setColumn(C1);C6.setManage(C14);C6.setParent(C0);C6.setRow(C3);C6.iC();C7.setColumn(C1);C7.setManage(C12);C7.setParent(C0);C7.setRow(C2);C7.setAlignment("TOPLEFT");C7.setSizing("FITTOWIDTH");C7.setFlow("DOWN");C7.setMarginBottom(10);C7.iC();C8.iC();C9.setDisplayPosition(1);C9.setParent(C8);C9.iC();C10.setDisplayPosition(1);C10.setParent(C8);C10.iC();C11.setAlignment("CENTERLEFT");C11.setColumn(C9);C11.setManage(C13);
C11.setParent(C8);C11.setRow(C10);C11.setSizing("FITTOWIDTH");C11.setMarginLeft(20);C11.iC();C12.setDisplayPosition(1);C12.setLeft(0);C12.setParent(this);C12.setTabPosition(2);C12.setTabStop(false);C12.setTop(0);C12.setWidth(800);C12.setStyle(l.gTh("XSTHEME01").get("PANELBORDERS1"));C12.setLayoutManager(C8);C12.iC();C13.setCaption("FEATURED PRODUCTS");C13.setDisplayPosition(1);C13.setEllipses("WORD");C13.setHeight(25);C13.setParent(C12);C13.setTabPosition(1);C13.setTabStop(false);C13.setTop(12);C13.setVerticalAlignment("CENTER");
C13.setWidth(778);C13.setStyle(l.gTh("XSTHEME01").get("TEXT12BOLDALMOSTBLACK"));C13.setLeft(20);C13.iC();C14.setDisplayPosition(2);C14.setLeft(0);C14.setParent(this);C14.setTabPosition(1);C14.setTop(60);C14.setWidth(800);C14.setHeight(365);C14.iC();C15.setCollects("XSPRDDTA");C15.iC();C16.iC();C16.aH("COMPLETED",this,e2);C14.aDS("XSPRDTIL");C14.aLF({});C15.aLF({"XSPRDID":f.F1,"XSPRDLNID":f.F2,"XSPRDCTID":f.F3,"XSPRDDSC":f.F4,"XSPRDMDL":f.F5,"XSPRDIMG":f.F6,"XSPRDSTS":f.F7,"XSPRDPRC":f.F8,"XSPRDDTL":f.F9});
this.setDisplayPosition(1);this.setHeight(425);this.setLeft(0);this.setTabPosition(1);this.setTop(0);this.setWidth(800);this.setLayoutManager(C0);this.aH("INITIALIZE",this,e1);}});function e1(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#COM_OWNER.Initialize",28);r.ln=28;{r.ln=30;m.LOADFEATUREPRODUCTS.mthEXECUTE({},{LIST:{"PRODUCTLIST":m.PRODUCTS}});}r.ln=32;r.e();};function e2(sender,Ps){var m=this.REF,r=l.eR(this,cO,"#LoadFeatureProducts.Completed",34);r.ln=34;{r.ln=36;{var i1=m.PRODUCTS.cI();while(i1.step())
{var PRODUCT=r.sR("PRODUCT",i1.item());r.ln=38;m.TILE.addEntry();r.ln=40;m.TILE.getCurrentItem().setRelatedReference(PRODUCT);r.ln=42;}i1.end();r.dR("PRODUCT");}}r.ln=44;r.e();};}(window["LANSA"]));